import React from 'react';
import {allPages} from '../lib/time.js';
import {api,currency,dateTime,shortDate,initials,idOf} from '../lib/api.js';
import {Icon,IconButton,Link,Button,Alert,Empty,Loading,PageHeader,SectionTitle,Pagination,SearchInput,Badge,Modal,DataForm,Metric} from '../components/UI.jsx';
const defs={
 courses:['LEARN WITH INTENTION','Find your learning path.','Courses published by your academy, with transparent fees and clear details.','courses','cap'],
 teachers:['MEET YOUR GUIDES','A teacher for your journey.','Explore approved teacher profiles. Choose a teacher when requesting a course.','teachers','users'],
 enrollments:['YOUR CONNECTIONS','Learning, together.','Track enrollment requests, approvals, and your active learning connections.','enrollments','cap'],
 classes:['MAKE TIME TO LEARN','Your learning timetable.','Scheduled lessons, live classroom access, and class status in one place.','classes','calendar'],
 attendance:['SHOWING UP MATTERS','Every lesson counts.','Attendance recorded by your teacher for each class. Separate lessons have separate records.','attendance','checkList'],
 assignments:['PRACTICE WITH PURPOSE','Small efforts. Real progress.','Review instructions, submit your work, and receive feedback from your teacher.','assignments','file'],
 fees:['CLEAR & TRANSPARENT','Your fee ledger.','Invoices and payment references, with administrator verification. No automatic charges.','fees','wallet'],
 users:['ACADEMY MANAGEMENT','People make the difference.','Review teacher applications and manage account access.','users','users'],
 students:['YOUR LEARNING COMMUNITY','Guide the next step.','Student profiles connected to your approved teaching enrollments.','students','users'],
 notifications:['STAY IN THE KNOW','Your academy updates.','Enrollment changes, scheduled lessons, assignments, and fee notices.','notifications','bell'],
 audit:['ACCOUNTABILITY MATTERS','A clear record of changes.','Administrative and authentication actions, without private message contents.','audit','shield']
};
const field=(name,label,type='text',extra={})=>({name,label,type,...extra});
const enrollmentLabel=e=>`${e.course?.name||'Course'} · ${e.student?.user?.name||'Student'} / ${e.ulma?.user?.name||'Teacher'}`;
const secureHref=value=>{try{const u=new URL(value);return u.protocol==='https:'?u.href:null;}catch{return null;}};
export class Academy extends React.Component{
 constructor(props){super(props);this.state={data:null,error:'',page:1,q:'',role:new URLSearchParams(location.search).get('role')||'',loading:true,modal:null,confirm:null,busy:false};}
 live=true;serial=0;timer=null;
 componentDidMount(){this.load();}componentWillUnmount(){this.live=false;clearTimeout(this.timer);}
 load=async()=>{const n=++this.serial;this.setState({loading:true,error:''});const query=new URLSearchParams({page:this.state.page,limit:12});if(this.state.q)query.set('q',this.state.q);if(this.props.type==='users'&&this.state.role)query.set('role',this.state.role);
  try{const data=await api(`/${defs[this.props.type][3]}?${query}`);if(this.live&&n===this.serial)this.setState({data,loading:false});}catch(e){if(this.live&&n===this.serial)this.setState({error:e.message,loading:false});}
 };
 perform=async(path,body,method='PATCH')=>{this.setState({busy:true});try{const r=await api(path,{method,body});this.props.app.toast(r.warning||r.message||'Changes saved.',r.warning?'error':'success');this.setState({confirm:null});await this.load();}catch(e){this.props.app.toast(e.message,'error');}finally{if(this.live)this.setState({busy:false});}};
 confirm=(title,description,path,body)=>this.setState({confirm:{title,description,path,body}});
 openForm=async(action,item={})=>{
  const {app,type}=this.props;const role=app.state.user?.role;let title='',fields=[],values={},method='POST',path='',note='';
  try{
   if(type==='courses'){
    if(action==='enroll'){
     return app.navigate(`/enroll?course=${item._id}`);
    }else{title=action==='edit'?'Edit course':'Publish a course';path=action==='edit'?`/courses/${item._id}`:'/courses';method=action==='edit'?'PATCH':'POST';values=item;fields=[field('name','Course name','text',{required:true,minLength:2,maxLength:100,full:true}),field('description','Description & learning outcomes','textarea',{required:true,minLength:10,maxLength:4000,full:true}),field('level','Level','select',{required:true,defaultValue:'All levels',options:['All levels','Beginner','Intermediate','Advanced']}),field('duration','Duration (months)','number',{required:true,min:1,max:120}),field('currency','Billing currency','select',{required:true,defaultValue:'PKR',options:['PKR','USD','GBP','EUR','AED','SAR','CAD','AUD']}),field('monthlyFee','Monthly fee','number',{required:true,min:0,step:'0.01'})];}
   }
   else if(type==='classes'||type==='assignments'||type==='fees'){
    if(type==='assignments'&&action!=='create'){
     title=action==='submit'?'Submit your assignment':'Review submission';path=`/assignments/${item._id}`;method='PATCH';note=item.description;
     if(action==='submit'){fields=[field('text','Your answer / practice notes','textarea',{required:true,full:true,maxLength:10000}),field('audioUrl','Optional HTTPS audio link','url',{full:true,hint:'Use a link you are authorized to share. Files are not uploaded to this app.'})];values=item.submission||{};}
     else{fields=[field('score','Score out of 100','number',{required:true,min:0,max:100}),field('feedback','Teacher feedback','textarea',{full:true,maxLength:4000})];note=`Instructions: ${item.description}\n\nStudent response: ${item.submission?.text||'No text response.'}`;}
    }else if(type==='fees'&&action==='claim'){
     title='Submit a payment reference';path=`/fees/${item._id}`;method='PATCH';note=`Invoice ${item.invoiceNumber} · ${currency(item.amount,item.currency||'PKR')}. Only submit after you have actually paid. This does not process a bank transfer.`;
     fields=[field('paymentMethod','Payment method','select',{required:true,options:['bank','easypaisa','jazzcash','cash','other']}),field('transactionId','Transfer / receipt reference','text',{required:true,minLength:3,maxLength:150,full:true})];
    }else{
     const enrollments=await api('/enrollments?limit=100');const active=enrollments.items.filter(e=>['active','approved',...(type==='fees'?['paused']:[])].includes(e.status));if(!active.length)return app.toast('An approved enrollment is required first.','error');
     fields=[field('enrollment','Enrollment','select',{required:true,full:true,options:active.map(e=>({value:e._id,label:enrollmentLabel(e)}))})];path=`/${type}`;
     if(type==='classes'){title='Schedule a lesson';fields.push(field('topic','Lesson topic','text',{required:true,minLength:2,maxLength:160,full:true}),field('utcStart','Start (your device time)','datetime-local',{required:true}),field('utcEnd','End (your device time)','datetime-local',{required:true}),field('notes','Lesson notes','textarea',{full:true,maxLength:2000,hint:'The private video room is created automatically when you start.'}));}
     else if(type==='assignments'){title='Create an assignment';fields.push(field('title','Assignment title','text',{required:true,minLength:2,maxLength:160,full:true}),field('description','Instructions','textarea',{required:true,minLength:5,maxLength:4000,full:true}),field('type','Assignment type','select',{required:true,defaultValue:'recitation',options:['recitation','memorization','understanding','test']}),field('dueDate','Due date (device time)','datetime-local',{required:true}));}
     else{title='Create a fee invoice';fields.push(field('amount','Amount (enrollment currency)','number',{required:true,min:0,step:'0.01'}),field('dueDate','Due date','date',{required:true}),field('description','Description / billing month','text',{required:true,full:true,maxLength:200}));note='Invoices are real records. Creating an invoice does not charge a student. Verify transfers before marking them paid.';}
    }
   }else if(type==='attendance'){
    const classes=await allPages(api,'/classes');const valid=classes.filter(c=>['ongoing','completed'].includes(c.status));if(!valid.length)return app.toast('Start or complete a class before marking attendance.','error');
    title='Record class attendance';path='/attendance';fields=[field('classId','Class','select',{required:true,full:true,options:valid.map(c=>({value:c._id,label:`${c.topic} · ${c.student?.user?.name} · ${dateTime(c.utcStart,app.state.user.timezone)}`}))}),field('status','Attendance status','select',{required:true,options:['present','late','absent']}),field('remarks','Remarks','textarea',{full:true,maxLength:1000})];
   }
   if(title)this.setState({modal:{title,fields,values,path,method,note,action,item}});
  }catch(e){app.toast(e.message,'error');}
 };
 submit=async form=>{const m=this.state.modal;let body={...form};if(m.action==='enroll')body.course=m.item._id;
  for(const key of ['utcStart','utcEnd'])if(body[key])body[key]=new Date(body[key]).toISOString();if(body.dueDate)body.dueDate=new Date(body.dueDate).toISOString();
  await api(m.path,{method:m.method,body});this.setState({modal:null});this.props.app.toast(m.action==='enroll'?'Enrollment request sent.':'Saved successfully.');this.load();
 };
 renderCard=item=>{
  const {app,type}=this.props,role=app.state.user?.role,admin=role==='admin',teacher=role==='ulma',busy=this.state.busy;
  if(type==='courses')return <article className={`course-card tone-${item.name.length%3}`} key={item._id}><div className="course-cover"><span className="course-icon"><Icon name="cap" size={34}/></span><Badge status={item.isActive?'neutral':'cancelled'}>{item.isActive?item.level||'All levels':'Unpublished'}</Badge><span className="course-decoration" aria-hidden="true">✧</span></div><div className="course-body"><h3>{item.name}</h3><p>{item.description}</p><div className="course-facts"><span><Icon name="clock" size={15}/>{item.duration} months</span><span><Icon name="users" size={15}/>Teacher-led</span></div><div className="course-price"><strong>{currency(item.monthlyFee,item.currency)}<small>/ month</small></strong>{admin?<IconButton name="edit" label="Edit course" onClick={()=>this.openForm('edit',item)}/>:<Button variant="subtle" icon="arrow" onClick={()=>teacher?app.navigate('/enrollments'):this.openForm('enroll',item)}>{teacher?'Enrollments':'Join course'}</Button>}</div>{!admin&&!teacher&&<Link app={app} to={`/teachers?course=${item._id}`} className="text-link">See available teachers <Icon name="users" size={16}/></Link>}{admin&&<Button variant="outline" disabled={busy} onClick={()=>this.confirm(item.isActive?'Unpublish this course?':'Publish this course?','Existing enrollment records will be kept.',`/courses/${item._id}`,{isActive:!item.isActive})}>{item.isActive?'Unpublish':'Publish'}</Button>}</div></article>;
  if(type==='teachers')return <article className="teacher-card" key={item._id}><span className="teacher-avatar">{initials(item.user?.name)}</span><Badge status="approved">Approved teacher</Badge><h3>{item.user?.name||'Teacher unavailable'}</h3><p>{item.bio||'This teacher has not added a biography yet.'}</p><div className="tags">{item.expertise?.map(e=><Badge status="neutral" key={e}>{e}</Badge>)}</div><small>{item.experience?`${item.experience} years of experience`:'Experience not provided'}{item.user?.country?` · ${item.user.country}`:''}</small><Link app={app} to="/courses" className="btn subtle">Choose a course <Icon name="arrow" size={16}/></Link></article>;
  if(type==='enrollments'){
   const actions={pending:['approved','rejected'],approved:['active','paused','completed','cancelled'],active:['paused','completed','cancelled'],paused:['active','cancelled','completed']};return <article key={item._id} className="record-card"><div className="card-top"><span className="course-icon"><Icon name="cap"/></span><Badge status={item.status}/></div><h3>{item.course?.name||'Course unavailable'}</h3><dl><div><dt>Student</dt><dd>{item.student?.user?.name||'Unavailable'}</dd></div><div><dt>Teacher</dt><dd>{item.ulma?.user?.name||'Unavailable'}</dd></div><div><dt>Monthly fee</dt><dd>{currency(item.monthlyFee,item.currency||'PKR')}</dd></div><div><dt>Requested</dt><dd>{shortDate(item.requestedAt||item.createdAt)}</dd></div></dl>{item.notes&&<p className="record-note">{item.notes}</p>}<div className="record-actions">{admin?(actions[item.status]||[]).map(status=><Button key={status} variant={status==='approved'||status==='active'?'':'outline'} disabled={busy} onClick={()=>this.confirm(`Change enrollment to ${status}?`,'Cancelled, completed, or rejected enrollments cannot be reopened through this interface.',`/enrollments/${item._id}`,{status})}>{status==='approved'?'Approve':status==='active'?'Activate':status==='rejected'?'Reject':status==='paused'?'Pause':status==='completed'?'Complete':'Cancel'}</Button>):role==='student'&&['pending','approved','active','paused'].includes(item.status)&&<Button variant="outline" disabled={busy} onClick={()=>this.confirm('Cancel this enrollment?','Scheduled classes for this enrollment will be cancelled and new messages will be disabled.',`/enrollments/${item._id}`,{status:'cancelled'})}>Cancel enrollment</Button>}{!admin&&['approved','active'].includes(item.status)&&<Link app={app} to="/messages" className="text-link">Messages <Icon name="message" size={16}/></Link>}</div></article>;
  }
  if(type==='classes')return <article key={item._id} className="class-card"><div className="card-top"><span className="date-tile"><strong>{new Date(item.utcStart).getDate()}</strong><small>{new Date(item.utcStart).toLocaleString('en',{month:'short'})}</small></span><Badge status={item.status}/></div><h3>{item.topic}</h3><p className="class-course">{item.course?.name||'Course unavailable'}</p><div className="class-details"><span><Icon name="clock" size={17}/>{dateTime(item.utcStart,app.state.user?.timezone)}</span><span><Icon name="users" size={17}/>{teacher?item.student?.user?.name:item.ulma?.user?.name||'Teacher unavailable'}</span></div><div className="record-actions">{teacher&&item.status==='scheduled'&&<Button disabled={busy} icon="play" onClick={()=>this.perform(`/classes/${item._id}`,{status:'ongoing'})}>Start class</Button>}{!admin&&['scheduled','ongoing'].includes(item.status)&&<Link app={app} to={`/class/${item._id}`} className={`btn ${item.status==='ongoing'?'':'subtle'}`}>Open classroom <Icon name="video" size={16}/></Link>}{teacher&&item.status==='ongoing'&&<Button variant="outline" disabled={busy} onClick={()=>this.confirm('End this lesson?','This marks the lesson completed and closes the built-in classroom.',`/classes/${item._id}`,{status:'completed'})}>Complete</Button>}{teacher&&['scheduled','ongoing'].includes(item.status)&&<IconButton name="close" label="Cancel class" disabled={busy} onClick={()=>this.confirm('Cancel this class?','Both participants will see that the class is cancelled.',`/classes/${item._id}`,{status:'cancelled'})}/>}</div></article>;
  if(type==='assignments')return <article className="assignment-card" key={item._id}><div className="card-top"><Badge status="neutral">{item.type}</Badge><Badge status={item.status}/></div><h3>{item.title}</h3><p>{item.description}</p><small className="due-date"><Icon name="calendar" size={15}/>Due {dateTime(item.dueDate,app.state.user?.timezone)}</small>{teacher&&<small>Student: {item.student?.user?.name||'Unavailable'}</small>}{item.submission?.text&&<details className="submission"><summary>View submitted work</summary><p>{item.submission.text}</p>{secureHref(item.submission.audioUrl)&&<a href={secureHref(item.submission.audioUrl)} target="_blank" rel="noreferrer">Open submitted audio link ↗</a>}</details>}{item.status==='graded'&&<div className="grade-box"><strong>{item.grade?.score} / {item.grade?.maxScore}</strong><p>{item.grade?.feedback||'No written feedback supplied.'}</p></div>}<div className="record-actions">{role==='student'&&!['graded','completed'].includes(item.status)&&<Button icon="send" variant="subtle" onClick={()=>this.openForm('submit',item)}>{item.status==='submitted'?'Update submission':'Submit work'}</Button>}{teacher&&item.status==='submitted'&&<Button icon="checkList" onClick={()=>this.openForm('grade',item)}>Grade submission</Button>}</div></article>;
  if(type==='students')return <article className="student-card" key={item._id}><span className="teacher-avatar">{initials(item.user?.name)}</span><h3>{item.user?.name||'Student unavailable'}</h3><p>{item.user?.email||'Email unavailable'}</p><small>{item.user?.country||'Country not specified'}</small><Link app={app} to="/enrollments" className="text-link">View enrollments <Icon name="arrow" size={16}/></Link></article>;
  return null;
 };
 renderTable=items=>{
  const {type,app}=this.props,admin=app.state.user?.role==='admin';let headers=[],rows=[];
  if(type==='fees'){headers=['Invoice','Student / description','Amount','Due date','Status','Actions'];rows=items.map(x=>[x.invoiceNumber,<div className="invoice-description"><strong>{x.student?.user?.name||''}</strong><small>{x.description}</small>{x.transactionId&&<small>Reference: {x.transactionId}</small>}</div>,currency(x.amount,x.currency||'PKR'),shortDate(x.dueDate),<Badge status={x.status}/>,<div className="row-actions">{admin&&!['paid','cancelled'].includes(x.status)?<><Button variant="subtle" disabled={this.state.busy} onClick={()=>this.confirm('Confirm this payment was received?','Only approve after checking your actual bank, wallet, or cash records. This app does not verify a transfer automatically.',`/fees/${x._id}`,{status:'paid'})}>Verify paid</Button>{x.status==='submitted'&&<Button variant="outline" disabled={this.state.busy} onClick={()=>this.perform(`/fees/${x._id}`,{status:'pending'})}>Return</Button>}<IconButton name="close" label="Cancel invoice" disabled={this.state.busy} onClick={()=>this.confirm('Cancel this invoice?','This will retain the record but close the invoice.',`/fees/${x._id}`,{status:'cancelled'})}/></>:!admin&&['pending','overdue'].includes(x.status)&&<Button variant="subtle" onClick={()=>this.openForm('claim',x)}>Submit reference</Button>}</div>]);}
  if(type==='users'){headers=['Name','Email','Role','Account','Teacher approval','Actions'];rows=items.map(x=>[<span className="person-cell"><span className="avatar">{initials(x.name)}</span><strong>{x.name}</strong></span>,x.email,<Badge status="neutral">{x.role==='ulma'?'Teacher':x.role}</Badge>,<Badge status={x.isActive?'active':'cancelled'}>{x.isActive?'Active':'Disabled'}</Badge>,x.role==='ulma'?<Badge status={x.approved?'approved':'pending'}>{x.approved?'Approved':'Pending'}</Badge>:'—',<div className="row-actions">{x.role!=='admin'&&<>{x.role==='ulma'&&<Button variant="subtle" disabled={this.state.busy} onClick={()=>this.confirm(x.approved?'Revoke teacher approval?':'Approve this teacher?',x.approved?'Teacher sessions will be signed out.':'Review the teacher’s identity and qualifications before approving access.',`/users/${x._id}`,{approved:!x.approved})}>{x.approved?'Revoke':'Approve'}</Button>}<Button variant="outline" disabled={this.state.busy} onClick={()=>this.confirm(x.isActive?'Disable this account?':'Enable this account?',x.isActive?'The account will be signed out on every device.':'The user will be able to sign in again, subject to teacher approval.',`/users/${x._id}`,{isActive:!x.isActive})}>{x.isActive?'Disable':'Enable'}</Button></>}</div>]);}
  if(type==='attendance'){headers=['Class','Date','Student','Teacher','Status','Remarks'];rows=items.map(x=>[x.classId?.topic||'Legacy attendance record',dateTime(x.classId?.utcStart||x.date,this.props.app.state.user?.timezone),x.student?.user?.name||'Unavailable',x.ulma?.user?.name||'Unavailable',<Badge status={x.status}/>,x.remarks||'—']);}
  if(type==='audit'){headers=['Time','Actor','Action','Record'];rows=items.map(x=>[dateTime(x.createdAt,app.state.user.timezone),x.actor?.name||'Unavailable',x.action,<code>{x.record||'—'}</code>]);}
  return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={items[i]._id}>{r.map((cell,j)=><td key={j} data-label={headers[j]}>{cell}</td>)}</tr>)}</tbody></table></div>;
 };
 render(){const {app,type}=this.props,[eyebrow,title,desc,,icon]=defs[type],{data,error,loading,modal,confirm}=this.state,role=app.state.user?.role,admin=role==='admin',teacher=role==='ulma';const creatable=(admin&&['courses','fees'].includes(type))||(teacher&&['classes','assignments','attendance'].includes(type));
  return <><PageHeader eyebrow={eyebrow} title={title} description={desc}>{creatable&&<Button icon="plus" onClick={()=>this.openForm('create')}>{type==='courses'?'Add course':type==='classes'?'Schedule lesson':type==='assignments'?'Add assignment':type==='attendance'?'Mark attendance':'Create invoice'}</Button>}{type==='notifications'&&<Button variant="outline" icon="check" disabled={this.state.busy} onClick={()=>this.perform('/notifications/read',{})}>Mark all read</Button>}</PageHeader>
  {['courses','users'].includes(type)&&<div className="resource-toolbar"><SearchInput value={this.state.q} onChange={q=>{this.setState({q});clearTimeout(this.timer);this.timer=setTimeout(()=>this.setState({page:1},this.load),350);}} placeholder={type==='users'?'Search people by name or email…':'Search courses…'}/>{type==='users'&&<select aria-label="Filter by role" value={this.state.role} onChange={e=>this.setState({role:e.target.value,page:1},this.load)}><option value="">All roles</option><option value="student">Students</option><option value="ulma">Teachers</option><option value="admin">Administrators</option></select>}<span>{data?.total??'—'} {type}</span></div>}
  {type==='classes'&&<div className="info-line"><Icon name="clock" size={16}/>Times displayed in {app.state.user?.timezone||'your device timezone'}. New lesson form uses your device’s local time.</div>}
  {type==='fees'&&<Alert kind="info">{data?.paymentInstructions||'Payment instructions have not been set by the administrator. Contact the academy before making a payment.'}</Alert>}
  {loading?<Loading/>:error?<Alert retry={this.load}>{error}</Alert>:data?.items.length?<>
  {['fees','users','attendance','audit'].includes(type)?this.renderTable(data.items):type==='notifications'?<div className="notice-list">{data.items.map(n=><article className={`notice-card ${n.read?'':'unread'}`} key={n._id}><span className="feature-icon"><Icon name="bell"/></span><div><h3>{n.title}</h3><p>{n.body}</p><small>{dateTime(n.createdAt,app.state.user.timezone)}</small></div>{n.href?.startsWith('/')&&!n.href.startsWith('//')&&<Link app={app} to={n.href} className="icon-btn" aria-label="Open notification"><Icon name="arrow"/></Link>}</article>)}</div>:<div className={`card-grid ${type==='teachers'?'teacher-grid':''}`}>{data.items.map(this.renderCard)}</div>}
  <Pagination {...data} onChange={page=>this.setState({page},this.load)}/></>:<div className="panel"><Empty icon={icon} title={type==='courses'?'Your academy’s courses will appear here':type==='users'?'No matching accounts':type==='notifications'?'You’re all caught up':`No ${type} yet`} text={type==='teachers'?'An administrator must approve teacher accounts before they appear here.':type==='fees'?'Invoices are generated after enrollment approval, or created by your administrator.':type==='enrollments'?'Choose a published course and a teacher to send your first request.':'Records will appear here when the relevant activity is created. No sample data is shown.'}>{type==='enrollments'&&role==='student'&&<Link app={app} to="/courses" className="btn">Explore courses <Icon name="arrow" size={16}/></Link>}</Empty></div>}
  {modal&&<Modal title={modal.title} onClose={()=>this.setState({modal:null})}>{modal.note&&<div className="form-note">{modal.note}</div>}<DataForm fields={modal.fields} values={modal.values} onSubmit={this.submit} label={modal.action==='enroll'?'Request enrollment':modal.action==='claim'?'Submit for verification':'Save changes'}/></Modal>}
  {confirm&&<Modal title={confirm.title} busy={this.state.busy} onClose={()=>this.setState({confirm:null})}><p>{confirm.description}</p><div className="modal-actions"><Button variant="outline" disabled={this.state.busy} onClick={()=>this.setState({confirm:null})}>Go back</Button><Button disabled={this.state.busy} onClick={()=>this.perform(confirm.path,confirm.body)}>{this.state.busy?'Saving…':'Confirm action'}</Button></div></Modal>}</>;
 }
}
export class Reports extends React.Component{
 state={month:new Date().toISOString().slice(0,7),data:null,error:''};live=true;
 componentDidMount(){this.load();}componentWillUnmount(){this.live=false;}
 load=async()=>{this.setState({data:null,error:''});try{const d=await api(`/reports?month=${this.state.month}`);if(this.live)this.setState({data:d});}catch(e){if(this.live)this.setState({error:e.message});}};
 render(){const {app,progress}=this.props,{data,error,month}=this.state;return <><PageHeader eyebrow={progress?'YOUR GROWTH':'MONTHLY OVERVIEW'} title={progress?'See how far you’ve come.':'A month of meaningful progress.'} description="Calculated from class records, teacher-marked attendance and graded assignments. Administrator reports contain aggregate figures only."><label className="month-picker">Report month<input type="month" value={month} onChange={e=>this.setState({month:e.target.value},this.load)}/></label><a className="btn outline" href={`/api/reports?month=${month}&format=csv`}><Icon name="download" size={17}/> Export CSV</a><Button variant="outline" icon="file" onClick={()=>window.print()}>Print report</Button></PageHeader>{error?<Alert retry={this.load}>{error}</Alert>:!data?<Loading/>:<><div className="metrics"><Metric icon="calendar" label="Scheduled records" value={data.totalClasses} note="Classes starting in this month (UTC)"/><Metric icon="checkList" label="Completed classes" value={data.completedClasses} note="Lessons marked completed"/><Metric icon="chart" label="Attendance" value={data.attendanceRate===null?'—':`${data.attendanceRate}%`} note="Present or late ÷ marked records"/><Metric icon="cap" label="Average score" value={data.averageScore===null?'—':`${data.averageScore}%`} note="Assignments graded this month"/></div><section className="panel"><SectionTitle title={data.aggregateOnly?"Academy summary":"Learning activity"} subtitle={data.aggregateOnly?"Detailed teaching records remain with their teacher and student.":"Your lesson records for the selected month."}/>{data.classes.length?<div className="activity-list">{data.classes.sort((a,b)=>new Date(b.utcStart)-new Date(a.utcStart)).map(c=><div className="activity-item" key={c._id}><span className="activity-dot"/><div><h3>{c.topic}</h3><p>{c.course?.name} · {dateTime(c.utcStart,app.state.user.timezone)}</p></div><Badge status={c.status}/></div>)}</div>:<Empty icon="chart" title={data.aggregateOnly?"Teaching is managed by teachers":"No activity in this month"} text={data.aggregateOnly?"Use the figures above for academy oversight. Assignments, attendance and classroom controls are not administrative actions.":"As lessons are completed and work is graded, your report will build itself from those records."}/>}</section><div className="source-note">A dash means there are no qualifying records. It is not a zero score. Reading-position saves indicate activity, not measured comprehension.</div></>}</>;}
}
