import React,{useEffect,useState} from 'react';
import {api} from '../lib/api.js';
import {allPages,deviceZone,titleCase} from '../lib/time.js';
import {LocationFields,PhotoPicker} from '../components/BookingUI.jsx';
import {PageHeader,SectionTitle,Button,IconButton,Icon,Alert,Loading,Badge,DataForm} from '../components/UI.jsx';
import {useResource} from './Scheduling.jsx';
const days=['monday','tuesday','wednesday','thursday','friday','saturday','sunday'];
const field=(name,label,type='text',rest={})=>({name,label,type,...rest});
function TeachingSettings({app}){
 const {data,error,loading,reload}=useResource('/teacher-profile'),[form,setForm]=useState(null),[courses,setCourses]=useState([]),[saving,setSaving]=useState(false),[failure,setFailure]=useState('');
 useEffect(()=>{if(data)setForm({...data,expertise:(data.expertise||[]).join(', '),courses:(data.courses||[]).map(c=>c._id||c),availability:data.availability||[],qualifications:data.qualifications||[]});},[data]);
 useEffect(()=>{let live=true;allPages(api,'/courses').then(d=>live&&setCourses(d)).catch(e=>live&&setFailure(e.message));return()=>{live=false;};},[]);
 const change=(k,v)=>setForm(f=>({...f,[k]:v}));
 const row=(index,patch)=>setForm(f=>({...f,availability:f.availability.map((r,i)=>i===index?{...r,...patch}:r)}));
 async function save(e){e.preventDefault();setSaving(true);setFailure('');try{await api('/teacher-profile',{method:'PATCH',body:{bio:form.bio,experience:form.experience,expertise:form.expertise,availability:form.availability,courses:form.courses,qualifications:form.qualifications}});app.toast('Teaching profile saved. Existing bookings have not moved.');reload();}catch(e){setFailure(e.message);}finally{setSaving(false);}}
 if(loading||!form&&!error)return <Loading label="Loading your teaching profile…"/>;if(error)return <Alert retry={reload}>{error}</Alert>;
 return <section className="panel settings-teaching"><SectionTitle title="Your teaching profile & weekly availability" subtitle={`All availability below uses ${app.state.user.timezone}. Students see the corresponding time in their own time zone.`}/>{failure&&<Alert>{failure}</Alert>}
 <form onSubmit={save} className="data-form"><div className="form-grid"><label className="field full"><span>About your teaching</span><textarea value={form.bio||''} maxLength={3000} rows={4} onChange={e=>change('bio',e.target.value)} placeholder="Explain your teaching style, experience and the students you can help."/></label><label className="field"><span>Years of teaching experience</span><input type="number" min="0" max="80" value={form.experience??0} onChange={e=>change('experience',e.target.value)}/></label><label className="field"><span>Expertise · comma separated</span><input value={form.expertise} maxLength={350} placeholder="Tajweed, Hifz, Arabic" onChange={e=>change('expertise',e.target.value)}/></label></div>
 <div className="settings-subsection"><h3>Courses you teach</h3><p className="muted">Select specific courses, or leave every box unchecked to accept requests for all active courses.</p><div className="course-checks">{courses.length?courses.map(c=><label className="check-card" key={c._id}><input type="checkbox" checked={form.courses.includes(c._id)} onChange={e=>change('courses',e.target.checked?[...form.courses,c._id]:form.courses.filter(id=>id!==c._id))}/><span><strong>{c.name}</strong><small>{c.level}</small></span></label>):<p>No active courses have been published yet.</p>}</div></div>
 <div className="settings-subsection"><h3>Weekly hours · {app.state.user.timezone}</h3><p className="muted">Add one or more windows per day. The academy’s lesson duration splits these windows into slots. Use 00:00 as the end for midnight; split overnight availability into two days. Existing bookings remain blocked even when you edit your hours.</p>
 {form.availability.length?<div className="availability-rows">{form.availability.map((r,i)=><div className={`availability-edit-row ${r.isActive===false?'inactive':''}`} key={i}><label className="field"><span>Day</span><select value={r.day} onChange={e=>row(i,{day:e.target.value})}>{days.map(d=><option key={d} value={d}>{titleCase(d)}</option>)}</select></label><label className="field"><span>From</span><input type="time" value={r.startTime} required step="60" onChange={e=>row(i,{startTime:e.target.value})}/></label><label className="field"><span>Until</span><input type="time" value={r.endTime==='24:00'?'00:00':r.endTime} required step="60" onChange={e=>row(i,{endTime:e.target.value})}/></label><label className="inline-check"><input type="checkbox" checked={r.isActive!==false} onChange={e=>row(i,{isActive:e.target.checked})}/> Open</label><IconButton type="button" name="trash" label={`Remove ${r.day} window ${i+1}`} onClick={()=>change('availability',form.availability.filter((_,j)=>j!==i))}/></div>)}</div>:<div className="form-note">You have no weekly availability yet. Students cannot request a new slot until you add an open window.</div>}
 <Button type="button" variant="outline" icon="plus" disabled={form.availability.length>=28} onClick={()=>change('availability',[...form.availability,{day:'monday',startTime:'09:00',endTime:'12:00',isActive:true}])}>Add availability window</Button></div>
 <div className="settings-subsection"><h3>Qualifications</h3><p className="muted">Only add genuine qualifications. The academy approval badge is not an independent certification of these details.</p>{form.qualifications.map((q,i)=><div className="qualification-edit-row" key={i}><label className="field"><span>Qualification</span><input value={q.degree} required maxLength={120} onChange={e=>change('qualifications',form.qualifications.map((x,j)=>j===i?{...x,degree:e.target.value}:x))}/></label><label className="field"><span>Institution</span><input value={q.institution||''} maxLength={160} onChange={e=>change('qualifications',form.qualifications.map((x,j)=>j===i?{...x,institution:e.target.value}:x))}/></label><label className="field"><span>Year</span><input type="number" min="1950" max={new Date().getFullYear()} value={q.year||''} onChange={e=>change('qualifications',form.qualifications.map((x,j)=>j===i?{...x,year:e.target.value}:x))}/></label><IconButton name="trash" label="Remove qualification" type="button" onClick={()=>change('qualifications',form.qualifications.filter((_,j)=>j!==i))}/></div>)}<Button type="button" variant="outline" icon="plus" disabled={form.qualifications.length>=12} onClick={()=>change('qualifications',[...form.qualifications,{degree:'',institution:'',year:''}])}>Add qualification</Button></div>
 <Button type="submit" disabled={saving} icon="check">{saving?'Saving teaching profile…':'Save teaching profile & availability'}</Button></form></section>;
}
function AcademySettings({app}){
 const {data,error,loading,reload}=useResource('/config');
 if(loading)return <Loading/>;if(error)return <Alert retry={reload}>{error}</Alert>;if(!data)return null;
 const b=data.booking;
 return <section className="panel settings-admin"><SectionTitle title="Academy & booking rules" subtitle="Only administrators can change these rules. Existing approved timetables and invoice amounts are not silently rewritten."/><div className="form-note"><Badge status={data.emailConfigured?'approved':'pending'}>{data.emailConfigured?'SMTP configured':'Email setup required'}</Badge> Email OTP is mandatory for account activation and sign-in. A configured status does not prove delivery to the recipient’s inbox.</div>
 <DataForm key={JSON.stringify(data)} values={{...data,...b}} fields={[
 field('academyName','Academy name','text',{required:true,minLength:2,maxLength:80}),field('contactEmail','Public contact email','email',{maxLength:254}),
 field('slotMinutes','Lesson duration (minutes)','select',{required:true,options:[15,20,30,45,60,90,120].map(v=>({value:v,label:`${v} minutes`}))}),
 field('holdHours','Pending request hold (hours)','number',{required:true,min:1,max:168,hint:'The hold ends sooner if the first lesson starts. No fee is created before approval.'}),
 field('bookingLeadHours','Minimum booking notice (hours)','number',{required:true,min:0,max:168}),
 field('bookingWindowDays','How far ahead can a course start? (days)','number',{required:true,min:7,max:180}),
 field('joinEarlyMinutes','Allow teacher to start early (minutes)','number',{required:true,min:0,max:30,hint:'Students can join only after the teacher starts the lesson.'}),
 field('feeGraceDays','Fee due-date grace (calendar days)','number',{required:true,min:0,max:30}),
 field('announcement','Public announcement','textarea',{full:true,maxLength:2000}),field('paymentInstructions','Payment instructions','textarea',{full:true,maxLength:3000,hint:'Official payment details only. Never publish private passwords or keys.'}),field('registrationOpen','Allow new registrations','checkbox',{full:true})
 ]} onSubmit={async values=>{const booking={};for(const k of Object.keys(b))if(values[k]!==undefined){booking[k]=Number(values[k]);delete values[k];}const r=await api('/config',{method:'PATCH',body:{...values,booking}});app.setState({academyName:r.academyName});app.toast('Academy booking rules saved.');reload();}}/></section>;
}
export default function AccountSettings({app}){
 const user=app.state.user,[form,setForm]=useState({...user,timezone:user.timezone||deviceZone(),languages:(user.languages||[]).join(', ')}),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 async function save(e){e.preventDefault();setSaving(true);setError('');try{const r=await api('/auth/profile',{method:'PATCH',body:{name:form.name,phone:form.phone,country:form.country,city:form.city,timezone:form.timezone,languages:form.languages,gender:form.gender,age:form.age,theme:form.theme,translation:form.translation}});app.updateUser(r.user);app.setTheme(r.user.theme);app.toast('Your profile and local-time preferences are saved.');}catch(e){setError(e.message);}finally{setSaving(false);}}
 return <><PageHeader eyebrow="A BETTER LEARNING CONNECTION" title="Your profile. Your availability." description="Keep your country, languages, photo and time zone up to date. Both sides see the same lesson in their own local time."/>
 <div className="settings-grid"><section className="panel"><SectionTitle title="Personal profile" subtitle={`${user.email} · email verified`}/><PhotoPicker user={user} onSaved={p=>{app.updateUser({profileImage:p.profileImage,photoVersion:p.photoVersion});app.toast(p.message);}}/>{error&&<Alert>{error}</Alert>}
 <form onSubmit={save} className="data-form"><LocationFields value={form} onChange={setForm} includeName/>
 <div className="form-grid"><label className="field"><span>Reading translation</span><select value={form.translation||'en'} onChange={e=>setForm(f=>({...f,translation:e.target.value}))}><option value="en">English</option><option value="ur">Urdu</option><option value="none">Arabic only</option></select></label><label className="field"><span>Appearance</span><select value={form.theme||'light'} onChange={e=>setForm(f=>({...f,theme:e.target.value}))}><option value="light">Light</option><option value="dark">Dark</option></select></label></div>
 {user.role==='ulma'&&<div className="form-note">Changing your teaching time zone is blocked while you have open enrollments. Updating your availability does not shift existing classes.</div>}
 <Button disabled={saving} type="submit" icon="check">{saving?'Saving profile…':'Save profile & preferences'}</Button></form></section>
 <section className="panel security-settings"><span className="security-illustration"><Icon name="shield" size={48}/></span><SectionTitle title="Password + email verification" subtitle="A fresh email code is required after your password at each sign-in. Codes expire after 10 minutes and can only be used once."/><div className="form-note">Never give another person your password or email verification code. We do not show private contact details in the public teacher directory.</div>
 <DataForm fields={[field('currentPassword','Current password','password',{required:true,full:true,autoComplete:'current-password'}),field('newPassword','New password','password',{required:true,full:true,minLength:10,maxLength:72,autoComplete:'new-password'})]} label="Update password" onSubmit={async body=>{await api('/auth/password',{method:'POST',body});app.signedOut();app.toast('Password changed. Sign in with your new password and email code.');}}/><p className="source-note">Private messages are encrypted in the database, not end-to-end encrypted. Changing a password signs out existing sessions.</p></section></div>
 {user.role==='ulma'&&<TeachingSettings app={app}/>} {user.role==='admin'&&<AcademySettings app={app}/>}
 </>;
}
