import React from 'react';
import {api,number,currency,dateTime} from '../lib/api.js';
import {Icon,Link,Button,Alert,Empty,Loading,PageHeader,SectionTitle,Metric,Badge} from '../components/UI.jsx';
export class Home extends React.Component{
 state={data:null,surahs:[],courses:[],error:'',libraryError:''};live=true;
 componentDidMount(){this.load();}componentWillUnmount(){this.live=false;}
 load=async()=>{try{const data=await api('/public');if(this.live)this.setState({data,error:''});}catch(e){if(this.live)this.setState({error:e.message});}
  api('/quran/surahs').then(d=>this.live&&this.setState({surahs:d.items,libraryError:''})).catch(e=>this.live&&this.setState({libraryError:e.message}));
  api('/courses?limit=3').then(d=>this.live&&this.setState({courses:d.items})).catch(()=>{});
 };
 render(){const {app}=this.props,{data,surahs,courses}=this.state;const featured=[1,18,36,55,67,112].map(n=>surahs.find(s=>s.number===n)).filter(Boolean);
 return <><div className="home-intro"><span><span className="small-dot"/> A MOMENT FOR WHAT MATTERS</span><span className="today-label">{new Intl.DateTimeFormat('en',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</span></div>
 <section className="hero"><div className="hero-copy"><span className="eyebrow">WELCOME TO YOUR LEARNING SPACE</span><h1>A little closer.<br/><em>Every day.</em></h1><p>Read the Quran. Discover the wisdom of Hadith.<br className="desktop-only"/> Build a meaningful connection, one lesson at a time.</p><div className="hero-actions"><Link to="/quran" app={app} className="btn">Open the Quran <Icon name="arrow" size={18}/></Link><Link to="/courses" app={app} className="btn outline">Explore classes</Link></div><div className="hero-foot"><span><Icon name="book" size={16}/> 114 surahs</span><i/><span>Arabic · English · Urdu</span></div></div><div className="hero-art" aria-hidden="true"><div className="arch arch-outer"><div className="arch arch-middle"><div className="arch arch-inner"><div className="art-star">✧</div><span className="art-arabic" lang="ar" dir="rtl">القرآن الكريم</span><span className="art-line"/><small>READ · REFLECT · GROW</small><div className="art-book"><Icon name="book" size={68}/></div></div></div></div><span className="floating-note"><Icon name="sparkle" size={16}/> Make space for reflection</span></div></section>
 {this.state.error&&<Alert retry={this.load}>{this.state.error}</Alert>}{data?.announcement&&<div className="announcement"><Icon name="bell"/>{data.announcement}</div>}
 <div className="feature-strip">{[['book','The Noble Quran','Read, listen & save your place','/quran'],['hadith','The Hadith library','Explore collections with references','/hadith'],['cap','Guided learning','Find your course and teacher','/courses']].map(([icon,title,sub,path])=><Link key={title} to={path} app={app} className="feature-link"><span className={`feature-icon ${icon}`}><Icon name={icon} size={25}/></span><div><strong>{title}</strong><small>{sub}</small></div><Icon name="arrow" size={18}/></Link>)}</div>
 <SectionTitle title="Open a surah. Find your focus." subtitle="A familiar beginning, or a new place to reflect."><Link app={app} to="/quran" className="text-link">View all surahs <Icon name="arrow" size={16}/></Link></SectionTitle>
 {featured.length?<div className="surah-grid home-surahs">{featured.map(s=><Link app={app} to={`/quran/${s.number}`} key={s.number} className="surah-card"><span className="surah-number">{s.number}</span><div><h3>{s.englishName}</h3><p>{s.englishNameTranslation} · {s.numberOfAyahs} ayahs</p></div><span className="arabic-name" dir="rtl" lang="ar">{s.name}</span></Link>)}</div>:<div className="library-onboarding"><Icon name="book" size={28}/><div><h3>Your Quran library belongs here</h3><p>{this.state.libraryError||'Connecting to the Quran library…'}</p></div><Link app={app} to="/quran" className="btn subtle">Open library</Link></div>}
 <div className="home-lower"><section className="reflection-panel"><div className="eyebrow">MAKE LEARNING A HABIT</div><h2>Small steps.<br/><em>Lasting connection.</em></h2><p>Save an ayah, revisit a Hadith, or join a lesson. Your next meaningful moment can start right here.</p><Link app={app} to={app.state.user?'/dashboard':'/register'} className="text-link">{app.state.user?'Go to your dashboard':'Start your learning journey'} <Icon name="arrow" size={17}/></Link><span className="reflection-watermark" aria-hidden="true">✧</span></section><section className="home-courses"><SectionTitle title="Learn with a teacher" subtitle="Real courses from your academy."><Link to="/courses" app={app} className="text-link">Browse <Icon name="arrow" size={15}/></Link></SectionTitle>{courses.length?courses.map((c,i)=><Link app={app} to="/courses" key={c._id} className="mini-course"><span className={`course-icon tone-${i}`}><Icon name="cap"/></span><div><strong>{c.name}</strong><small>{c.level||'All levels'} · {c.duration} months</small></div><span>{currency(c.monthlyFee,c.currency)}</span></Link>):<Empty icon="cap" title="Courses are being prepared" text="Published courses will appear here as soon as an administrator adds them."/>}<div className="live-counts"><span>{data?number(data.courses):'—'} published courses</span><span>{data?number(data.teachers):'—'} approved teachers</span><Badge status="neutral">Live records</Badge></div></section></div></>;
 }
}
export class Dashboard extends React.Component{
 state={data:null,error:''};live=true;
 componentDidMount(){this.load();}componentWillUnmount(){this.live=false;}
 load=async()=>{try{const d=await api('/dashboard');if(this.live)this.setState({data:d,error:''});}catch(e){if(this.live)this.setState({error:e.message});}};
 render(){const {app}=this.props,u=app.state.user,{data,error}=this.state;if(error)return <Alert retry={this.load}>{error}</Alert>;if(!data)return <Loading/>;
 const c=data.counts,admin=u.role==='admin',teacher=u.role==='ulma';
 return <><PageHeader eyebrow={admin?'ACADEMY OVERVIEW':teacher?'YOUR TEACHING SPACE':'YOUR LEARNING JOURNEY'} title={<>Assalamu alaikum, {u.name.split(' ')[0]}<span className="greeting-spark">✧</span></>} description={admin?'A clear view of your academy, grounded in real records.':teacher?'A meaningful lesson can make a lasting difference.':'A fresh opportunity to learn, reflect, and grow.'}><Link app={app} to="/quran" className="btn" >Continue reading <Icon name="arrow" size={18}/></Link></PageHeader>
 <div className="metrics">{admin?<><Metric icon="users" label="Registered users" value={number(c.users)} note="All account roles"/><Metric icon="cap" label="Active courses" value={number(c.courses)} note="Published by your academy"/><Metric icon="checkList" label="Pending enrollments" value={number(c.pendingEnrollments)} note="Awaiting your approval"/><Metric icon="wallet" label="Verified payments" value={Object.entries(c.feeTotals||{}).length?Object.entries(c.feeTotals).map(([code,v])=><span className="currency-line" key={code}>{currency(v.paid,code)}</span>):'No payments'} note="Admin-confirmed invoices"/></>:<><Metric icon="book" label={teacher?'Active enrollments':'Your courses'} value={number(c.enrollments)} note="Approved and active enrollments"/><Metric icon="calendar" label="Completed classes" value={number(c.classes)} note="Recorded in your timetable"/><Metric icon="chart" label="Attendance" value={c.attendance===null?'—':`${c.attendance}%`} note="Based on marked attendance"/><Metric icon="checkList" label="Open assignments" value={number(c.assignments)} note="Not yet submitted"/></>}</div>
 <div className="dashboard-grid"><section className="panel"><SectionTitle title="Coming up next" subtitle="Your next scheduled lessons."><Link app={app} to="/classes" className="text-link">Timetable <Icon name="arrow" size={16}/></Link></SectionTitle>{data.classes.length?<div className="upcoming-list">{data.classes.map(cl=><div className="upcoming-item" key={cl._id}><span className="date-tile"><strong>{new Date(cl.utcStart).getDate()}</strong><small>{new Date(cl.utcStart).toLocaleString('en',{month:'short'})}</small></span><div><h3>{cl.topic}</h3><p>{dateTime(cl.utcStart,u.timezone)}</p><small>{cl.course?.name} · {teacher?cl.student?.user?.name:cl.ulma?.user?.name}</small></div><Badge status={cl.status}/><Link app={app} to={`/class/${cl._id}`} className="icon-btn" aria-label="Open class"><Icon name="arrow"/></Link></div>)}</div>:<Empty icon="calendar" title="A little breathing room" text={teacher||admin?'Schedule a lesson for an approved enrollment to see it here.':'Your teacher’s scheduled lessons will appear here after your enrollment is approved.'}><Link app={app} to={teacher||admin?'/classes':'/courses'} className="btn subtle">{teacher||admin?'Manage classes':'Explore courses'}</Link></Empty>}</section><section className="continue-card"><span className="eyebrow">YOUR NEXT MOMENT</span><Icon name="book" size={38}/><h2>Return to<br/>your reading.</h2><p>Surah {u.reading?.surah||1} · Ayah {u.reading?.ayah||1}</p><Link app={app} to={`/quran/${u.reading?.surah||1}?ayah=${u.reading?.ayah||1}`} className="btn cream">Pick up where you left off <Icon name="arrow" size={17}/></Link><small>{number(u.bookmarks?.length)} saved references · {number(c.readingDays)} reading days</small></section></div>
 <SectionTitle title={admin?'Recent enrollment requests':teacher?'Your teaching connections':'Your learning connections'} subtitle="Every record here comes from your academy database."><Link app={app} to="/enrollments" className="text-link">View all <Icon name="arrow" size={16}/></Link></SectionTitle>{data.enrollments.length?<div className="card-grid">{data.enrollments.map(e=><article key={e._id} className="enrollment-card"><div className="card-top"><span className="course-icon"><Icon name="cap"/></span><Badge status={e.status}/></div><h3>{e.course?.name||'Course unavailable'}</h3><p>{teacher?e.student?.user?.name:e.ulma?.user?.name||'Teacher unavailable'}</p><div className="card-bottom"><span>{currency(e.monthlyFee,e.currency||'PKR')}</span><Link app={app} to="/enrollments" className="text-link">Details <Icon name="right" size={16}/></Link></div></article>)}</div>:<div className="panel"><Empty title="Your next chapter is waiting" text={admin?'New enrollment requests will appear here.':'Browse available courses and choose the right learning path.'} icon="cap"/></div>}</>;
 }
}
