import React from 'react';
import {api,normal,storeGet,storeSet,hrefForBookmark} from '../lib/api.js';
import {Icon,Link,Button,IconButton,Alert,Empty,Loading,PageHeader,SectionTitle,Badge,Pagination,SearchInput} from '../components/UI.jsx';
const sourceNote=<span>Quran text: Al Quran Cloud · English: Sahih International · Urdu: Fateh Muhammad Jalandhry.</span>;
async function copyText(app,value){try{await navigator.clipboard.writeText(value);app.toast('Copied with its reference.');}catch{app.toast('Clipboard is unavailable. Use HTTPS or select the text to copy it.','error');}}
export class QuranIndex extends React.Component{
 state={items:[],q:'',error:'',loading:true};live=true;
 componentDidMount(){this.load();}componentWillUnmount(){this.live=false;}
 load=async()=>{this.setState({loading:true,error:''});try{const d=await api('/quran/surahs');if(this.live)this.setState({items:d.items,loading:false});}catch(e){if(this.live)this.setState({error:e.message,loading:false});}};
 render(){const {app}=this.props,q=normal(this.state.q),items=this.state.items.filter(s=>normal(`${s.number} ${s.name} ${s.englishName} ${s.englishNameTranslation}`).includes(q));const u=app.state.user,last=u?.reading||storeGet('noor-reading',{surah:1,ayah:1});
 return <><PageHeader eyebrow="THE NOBLE QURAN" title="Read with presence." description="Arabic text, English and Urdu translations, and verse-by-verse recitation."><Link app={app} to={`/quran/${last.surah}?ayah=${last.ayah}`} className="btn" >Continue reading <Icon name="arrow" size={18}/></Link></PageHeader><section className="library-banner"><div><span className="eyebrow">A CONNECTION TO RETURN TO</span><h2>Your Quran. Your pace.</h2><p>Choose a surah, save your place, and make room for reflection.</p></div><span className="banner-arabic" lang="ar" dir="rtl">القرآن الكريم</span></section><div className="library-toolbar"><div className="tabs"><span className="active">Surah index</span><Link app={app} to="/bookmarks">Saved references</Link></div><SearchInput value={this.state.q} onChange={q=>this.setState({q})} placeholder="Find a surah by name or number…"/></div>
 {this.state.loading?<Loading label="Opening the Quran library…"/>:this.state.error?<Alert retry={this.load}>{this.state.error}</Alert>:items.length?<div className="surah-grid">{items.map(s=><Link to={`/quran/${s.number}`} app={app} className="surah-card" key={s.number}><span className="surah-number">{s.number}</span><div><h3>{s.englishName}</h3><p>{s.englishNameTranslation}</p><small>{s.revelationType} · {s.numberOfAyahs} ayahs</small></div><span className="arabic-name" dir="rtl" lang="ar">{s.name}</span></Link>)}</div>:<Empty icon="search" title="No matching surah" text="Try a different name or number. To search verse text, use the main search."/>}<div className="source-note"><Icon name="shield" size={15}/>{sourceNote}<a href="https://alquran.cloud/api" target="_blank" rel="noreferrer">View source</a></div></>;
 }
}
export class Reader extends React.Component{
 constructor(props){super(props);this.state={surah:null,items:[],error:'',translation:props.app.state.user?.translation||storeGet('noor-translation','en'),font:storeGet('noor-font',32),current:-1,playing:false,audioError:'',q:'',continuous:true};}
 audio=React.createRef();live=true;
 componentDidMount(){this.load();}componentWillUnmount(){this.live=false;this.audio.current?.pause();}
 load=async()=>{try{const [surah,index]=await Promise.all([api(`/quran/surahs/${this.props.number}`),api('/quran/surahs')]);if(!this.live)return;this.setState({surah,items:index.items,error:''},()=>{const a=new URLSearchParams(location.search).get('ayah');if(a)setTimeout(()=>document.getElementById(`ayah-${a}`)?.scrollIntoView({block:'center'}),120);});}catch(e){if(this.live)this.setState({error:e.message});}};
 play=i=>{if(i<0||i>=this.state.surah.ayahs.length){this.audio.current?.pause();this.setState({playing:false});return;}this.setState({current:i,audioError:''},()=>{const a=this.audio.current;a.src=this.state.surah.ayahs[i].audio;a.load();a.play().then(()=>this.live&&this.setState({playing:true})).catch(()=>this.live&&this.setState({playing:false,audioError:'Recitation could not play. Audio requires internet access to the recitation CDN.'}));});};
 toggle=()=>{if(this.state.current<0)return this.play(0);if(this.state.playing){this.audio.current.pause();this.setState({playing:false});}else this.audio.current.play().then(()=>this.setState({playing:true})).catch(()=>this.setState({audioError:'Tap an ayah’s play button to retry audio.'}));};
 mark=async ayah=>{const s=this.state.surah;try{if(this.props.app.state.user){const r=await api('/reading',{method:'POST',body:{surah:s.number,ayah}});this.props.app.updateUser({reading:r.reading});}else storeSet('noor-reading',{surah:s.number,ayah});this.props.app.toast('Reading position saved.');}catch(e){this.props.app.toast(e.message,'error');}};
 render(){const {app}=this.props,{surah:s,error,items,translation,font}=this.state;if(error)return <Alert retry={this.load}>{error}</Alert>;if(!s)return <Loading label="Preparing your reading space…"/>;
 const saved=app.bookmarks(),filtered=items.filter(x=>normal(`${x.englishName} ${x.name} ${x.number}`).includes(normal(this.state.q)));
 return <><div className="reader-top"><Link to="/quran" app={app} className="back-link"><Icon name="left" size={17}/> Surah index</Link><span className="reader-breadcrumb">The Noble Quran <Icon name="right" size={13}/> {s.englishName}</span><Link app={app} to="/bookmarks" className="text-link"><Icon name="bookmark" size={16}/> Saved</Link></div><div className="reader-layout"><aside className="reader-sidebar"><h3>Choose a surah</h3><SearchInput value={this.state.q} onChange={q=>this.setState({q})} placeholder="Search surahs…"/><nav aria-label="Surah navigation">{filtered.map(x=><Link app={app} to={`/quran/${x.number}`} key={x.number} className={x.number===s.number?'active':''}><span>{String(x.number).padStart(2,'0')}</span><div><strong>{x.englishName}</strong><small>{x.numberOfAyahs} ayahs</small></div><span className="arabic-name" lang="ar" dir="rtl">{x.name}</span></Link>)}</nav></aside><section className="reader-content"><header className="surah-heading"><span className="eyebrow">SURAH {s.number} · {s.revelationType?.toUpperCase()}</span><h1 lang="ar" dir="rtl">{s.name}</h1><h2>{s.englishName}</h2><p>{s.englishNameTranslation} <span>·</span> {s.ayahs.length} ayahs</p><div className="surah-ornament" aria-hidden="true"><span/>✧<span/></div></header><div className="reader-controls"><label>Translation<select value={translation} onChange={e=>{storeSet('noor-translation',e.target.value);this.setState({translation:e.target.value});}}><option value="en">English</option><option value="ur">Urdu</option><option value="none">Arabic only</option></select></label><label className="font-control">Arabic size<input aria-label="Arabic font size" type="range" min="24" max="46" value={font} onChange={e=>{storeSet('noor-font',Number(e.target.value));this.setState({font:Number(e.target.value)});}}/></label><label className="mobile-surah-select">Surah<select value={s.number} onChange={e=>app.navigate(`/quran/${e.target.value}`)}>{items.map(x=><option key={x.number} value={x.number}>{x.number}. {x.englishName}</option>)}</select></label></div>
 <div className="ayahs">{s.ayahs.map((a,i)=>{const ref=`quran:${s.number}:${a.numberInSurah}`;return <article id={`ayah-${a.numberInSurah}`} className={`ayah-card ${this.state.current===i?'listening':''}`} key={a.number}><div className="ayah-meta"><span className="verse-reference">{s.number}:{a.numberInSurah}</span><div><IconButton name="play" label={`Listen to ayah ${a.numberInSurah}`} onClick={()=>this.play(i)}/><IconButton name="bookmark" label={saved.includes(ref)?'Remove bookmark':'Save ayah'} aria-pressed={saved.includes(ref)} onClick={()=>app.toggleBookmark(ref)}/><IconButton name="copy" label="Copy ayah and reference" onClick={()=>copyText(app,`${a.text}\n${translation==='none'?'':a[translation]||''}\nQuran ${s.number}:${a.numberInSurah} · ${translation==='none'?'Arabic Uthmani text':translation==='ur'?'Jalandhry':'Sahih International'}`)}/><IconButton name="check" label="Mark as last read" onClick={()=>this.mark(a.numberInSurah)}/></div></div><p className="ayah-arabic" lang="ar" dir="rtl" style={{fontSize:`${font}px`}}>{a.text}<span className="ayah-end">{a.numberInSurah.toLocaleString('ar')}</span></p>{translation!=='none'&&<div className={`ayah-translation ${translation==='ur'?'urdu':''}`} lang={translation} dir={translation==='ur'?'rtl':'ltr'}><small>{translation==='ur'?'فتح محمد جالندھری':'SAHIH INTERNATIONAL'}</small><p>{a[translation]||'This translation is unavailable in the installed edition.'}</p></div>}</article>;})}</div><div className="surah-navigation">{s.number>1?<Link app={app} to={`/quran/${s.number-1}`} className="btn subtle"><Icon name="left" size={17}/> Previous surah</Link>:<span/>}{s.number<114&&<Link app={app} to={`/quran/${s.number+1}`} className="btn subtle">Next surah <Icon name="right" size={17}/></Link>}</div><div className="source-note">{sourceNote}</div></section></div>
 <div className="audio-dock"><audio ref={this.audio} onEnded={()=>this.state.continuous?this.play(this.state.current+1):this.setState({playing:false})} onError={()=>this.setState({playing:false,audioError:'Audio is unavailable. Check your internet connection and try another ayah.'})}/><div className="audio-details"><span className="audio-disc"><Icon name="volume"/></span><div><strong>{s.englishName}{this.state.current>=0?` · Ayah ${this.state.current+1}`:''}</strong><small>Mishary Rashid Alafasy</small></div></div><div className="audio-buttons"><IconButton name="left" label="Previous ayah" disabled={this.state.current<=0} onClick={()=>this.play(this.state.current-1)}/><button className="play-main" aria-label={this.state.playing?'Pause recitation':'Play recitation'} onClick={this.toggle}><Icon name={this.state.playing?'pause':'play'}/></button><IconButton name="right" label="Next ayah" disabled={this.state.current>=s.ayahs.length-1} onClick={()=>this.play(this.state.current+1)}/></div><label className="continuous"><input type="checkbox" checked={this.state.continuous} onChange={e=>this.setState({continuous:e.target.checked})}/> Continue playback</label>{this.state.audioError&&<p role="alert" className="audio-error">{this.state.audioError}</p>}</div></>;
 }
}
export class Hadith extends React.Component{
 constructor(props){super(props);const q=new URLSearchParams(location.search);this.state={books:[],data:null,error:'',book:q.get('book')||'bukhari',lang:q.get('lang')||'eng',q:q.get('q')||'',section:'',page:1,loading:true,expanded:{}};}
 serial=0;live=true;timer=null;
 componentDidMount(){api('/hadith/books').then(d=>this.live&&this.setState({books:d.items})).catch(()=>{});this.load();}componentWillUnmount(){this.live=false;clearTimeout(this.timer);}
 load=async()=>{const serial=++this.serial;this.setState({loading:true,error:''});const {book,lang,q,section,page}=this.state;try{const d=await api(`/hadith?${new URLSearchParams({book,lang,q,section,page})}`);if(this.live&&serial===this.serial)this.setState({data:d,loading:false});}catch(e){if(this.live&&serial===this.serial)this.setState({error:e.message,loading:false});}};
 change=values=>this.setState({...values,page:1,expanded:{}},this.load);
 render(){const {app}=this.props,{books,data,book,lang,q,section,error,loading}=this.state,saved=app.bookmarks();const selected=books.find(b=>b.id===book);return <><PageHeader eyebrow="THE HADITH LIBRARY" title="Wisdom to live by." description="Read source-linked collections, search their text, and keep meaningful references close."/><div className="hadith-book-tabs">{(books.length?books:[{id:'bukhari',name:'Sahih al-Bukhari'},{id:'muslim',name:'Sahih Muslim'},{id:'nawawi',name:'Forty Hadith of an-Nawawi'}]).map(b=><button className={`hadith-book ${book===b.id?'active':''}`} key={b.id} onClick={()=>this.change({book:b.id,lang:b.id==='nawawi'&&lang==='urd'?'eng':lang,section:'',q:''})}><span className="hadith-book-icon"><Icon name="hadith" size={25}/></span><div><strong>{b.name}</strong><small>{b.total!=null?`${b.total.toLocaleString()} English entries`:b.available===false?'Data not installed':'Explore collection'}</small></div><Icon name="right" size={17}/></button>)}</div>
 <div className="hadith-toolbar"><SearchInput value={q} onChange={v=>{this.setState({q:v});clearTimeout(this.timer);this.timer=setTimeout(()=>this.change({}),450);}} onSubmit={()=>this.change({})} placeholder="Search this collection or enter a hadith number…"/><label>Language<select value={lang} onChange={e=>this.change({lang:e.target.value,section:''})}><option value="eng">English</option><option value="ara">Arabic</option>{book!=='nawawi'&&<option value="urd">Urdu</option>}</select></label><label>Chapter<select value={section} onChange={e=>this.change({section:e.target.value})}><option value="">All chapters</option>{Object.entries(data?.sections||{}).filter(([,name])=>name).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label></div>
 {loading?<Loading label="Opening the collection…"/>:error?<Alert retry={this.load}>{error}</Alert>:<><div className="results-heading"><h2>{data.book.name}</h2><span>{data.total.toLocaleString()} matching entries</span></div><div className="hadith-list">{data.items.length?data.items.map(h=>{const ref=`hadith:${book}:${lang}:${h.hadithnumber}`,open=this.state.expanded[ref];return <article className="hadith-card" key={`${h.hadithnumber}-${h.reference?.hadith}`}><div className="hadith-card-top"><div><span className="hadith-number">{String(h.hadithnumber).padStart(2,'0')}</span><span><strong>{data.book.name}</strong><small>Book {h.reference?.book??'—'} · Hadith {h.reference?.hadith??h.hadithnumber}</small></span></div><div className="row-actions"><IconButton name="bookmark" label={saved.includes(ref)?'Remove saved hadith':'Save hadith'} aria-pressed={saved.includes(ref)} onClick={()=>app.toggleBookmark(ref)}/><IconButton name="copy" label="Copy hadith and source" onClick={()=>copyText(app,`${h.text}\n${data.book.name} #${h.hadithnumber} (${lang})\n${data.source}`)}/></div></div><div className={`hadith-text ${lang!=='eng'?'rtl-text':''} ${open||h.text.length<=800?'expanded':''}`} dir={lang==='eng'?'ltr':'rtl'} lang={lang==='ara'?'ar':lang==='urd'?'ur':'en'}>{h.text}</div>{h.text.length>800&&<button className="text-btn" onClick={()=>this.setState(s=>({expanded:{...s.expanded,[ref]:!open}}))}>{open?'Show less':'Read full hadith'} <Icon name="right" size={14}/></button>}<footer><span><Icon name="file" size={14}/> Reference #{h.hadithnumber}</span>{h.grades?.length?h.grades.map((g,i)=><Badge key={i} status="neutral">{g.name}: {g.grade}</Badge>):<small>No separate grade supplied in this edition.</small>}</footer></article>;}):<Empty icon="search" title="No matching hadith" text="Try a shorter keyword, another chapter, or a different language."/>}</div><Pagination {...data} onChange={page=>this.setState({page,expanded:{}},this.load)}/></>}
 <div className="source-note"><Icon name="info" size={16}/><span>Text, numbering and grades are displayed as supplied by the edition. Translations and numbering can differ between editions. Seek qualified guidance for interpretation.</span><a href="https://github.com/fawazahmed0/hadith-api" target="_blank" rel="noreferrer">Data source</a></div></>;
 }
}
export class Bookmarks extends React.Component{
 render(){const {app}=this.props,saved=app.bookmarks();return <><PageHeader eyebrow="YOUR PERSONAL COLLECTION" title="Keep what matters close." description={app.state.user?'Saved references are stored in your account.':'Guest bookmarks are saved only in this browser. Sign in for account-based saving.'}/>{saved.length?<div className="card-grid">{saved.map(ref=>{const p=ref.split(':');return <article className="saved-card" key={ref}><span className="course-icon"><Icon name={p[0]==='quran'?'book':'hadith'}/></span><Badge status="neutral">{p[0]==='quran'?'Quran':'Hadith'}</Badge><h3>{p[0]==='quran'?`Surah ${p[1]} · Ayah ${p[2]}`:`${p[1]} · Hadith ${p[3]}`}</h3><p>{p[0]==='quran'?'Return to the ayah and its translation.':`Saved edition: ${p[2]}`}</p><div className="card-bottom"><Link app={app} to={hrefForBookmark(ref)} className="text-link">Open reference <Icon name="arrow" size={17}/></Link><IconButton name="trash" label="Remove saved reference" onClick={()=>app.toggleBookmark(ref)}/></div></article>;})}</div>:<div className="panel"><Empty icon="bookmark" title="A collection that grows with you" text="Tap the bookmark icon on any ayah or hadith to find it here later."><Link app={app} to="/quran" className="btn">Explore the Quran <Icon name="arrow" size={17}/></Link></Empty></div>}</>;}
}
export class SearchPage extends React.Component{
 constructor(props){super(props);this.state={q:new URLSearchParams(location.search).get('q')||'',tab:'quran',book:'bukhari',lang:'eng',data:null,error:'',loading:false,page:1};}
 live=true;serial=0;componentDidMount(){if(this.state.q.trim().length>=2)this.load();}componentWillUnmount(){this.live=false;}
 load=async()=>{const serial=++this.serial;const {q,tab,book,lang,page}=this.state;if(q.trim().length<2)return;this.setState({loading:true,error:''});let path=tab==='quran'?`/quran/search?q=${encodeURIComponent(q)}&page=${page}`:tab==='hadith'?`/hadith?${new URLSearchParams({book,lang,q,page})}`:`/courses?q=${encodeURIComponent(q)}&page=${page}`;try{const d=await api(path);if(this.live&&serial===this.serial)this.setState({data:d,loading:false});}catch(e){if(this.live&&serial===this.serial)this.setState({error:e.message,loading:false});}};
 render(){const {app}=this.props,{q,tab,data,error,loading}=this.state;return <><PageHeader eyebrow="EXPLORE & DISCOVER" title="Find your next connection." description="Search Quran translations and Arabic text, Hadith editions, or your academy’s courses."/><div className="global-search-row"><SearchInput value={q} onChange={q=>this.setState({q})} onSubmit={()=>this.setState({page:1},this.load)} placeholder="Search a word, phrase or reference…"/><Button icon="search" onClick={()=>this.setState({page:1},this.load)}>Search</Button></div><div className="tabs search-tabs">{['quran','hadith','courses'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>this.setState({tab:t,page:1,data:null},this.load)}>{t==='quran'?'The Quran':t==='hadith'?'Hadith':'Courses'}</button>)}{tab==='hadith'&&<><select aria-label="Hadith collection" value={this.state.book} onChange={e=>this.setState({book:e.target.value,page:1,lang:e.target.value==='nawawi'&&this.state.lang==='urd'?'eng':this.state.lang},this.load)}><option value="bukhari">Sahih al-Bukhari</option><option value="muslim">Sahih Muslim</option><option value="nawawi">An-Nawawi</option></select><select aria-label="Hadith search language" value={this.state.lang} onChange={e=>this.setState({lang:e.target.value,page:1},this.load)}><option value="eng">English</option><option value="ara">Arabic</option>{this.state.book!=='nawawi'&&<option value="urd">Urdu</option>}</select></>}</div>
 {loading?<Loading label="Searching source text…"/>:error?<Alert retry={this.load}>{error}</Alert>:data?<><div className="results-heading"><h2>{data.total.toLocaleString()} results</h2><span>for “{q}”</span></div><div className="search-results">{data.items.length?data.items.map((item,i)=><article className="search-result" key={i}><div className="eyebrow">{tab==='quran'?`${item.surahName} · ${item.surah}:${item.numberInSurah}`:tab==='hadith'?`${data.book.name} #${item.hadithnumber}`:item.level||'ACADEMY COURSE'}</div>{tab==='quran'?<><p className="result-arabic" dir="rtl" lang="ar">{item.text}</p><p>{item.en}</p><p dir="rtl" className="urdu">{item.ur}</p><Link app={app} to={`/quran/${item.surah}?ayah=${item.numberInSurah}`} className="text-link">Read in context <Icon name="arrow" size={16}/></Link></>:tab==='hadith'?<><p className="result-excerpt" dir={this.state.lang==='eng'?'ltr':'rtl'}>{item.text}</p><Link app={app} to={`/hadith?book=${this.state.book}&lang=${this.state.lang}&q=${item.hadithnumber}`} className="text-link">Open full hadith <Icon name="arrow" size={16}/></Link></>:<><h3>{item.name}</h3><p>{item.description}</p><Link app={app} to="/courses" className="text-link">View courses <Icon name="arrow" size={16}/></Link></>}</article>):<Empty icon="search" title="No results found" text="Try another phrase or a different category."/>}</div><Pagination {...data} onChange={page=>this.setState({page},this.load)}/></>:<Empty icon="search" title="Start with a word or a reference" text="Enter at least two characters. Quran references such as 2:255 are supported."/>}</>;}
}
