import React,{useState,useEffect,useMemo,useCallback} from 'react';
import {api,currency,idOf} from '../lib/api.js';
import {allPages,viewerZone,localDate,shiftDate,dayTitle,atZone,timeOnly,rangeAt,titleCase} from '../lib/time.js';
import {countries} from '../lib/countries.js';
import {Icon,Link,Button,Alert,Loading,Empty,PageHeader,SectionTitle,Pagination,Badge,Modal,DataForm} from '../components/UI.jsx';
import {Avatar,TeacherSummary,ZoneClocks,DualTime} from '../components/BookingUI.jsx';

export function useResource(path,{poll=0}={}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
 useEffect(()=>{
  if(!path){setData(null);setError('');setLoading(false);return;}
  let live=true,serial=0;const controller=new AbortController();
  const load=async(initial=false)=>{const request=++serial;if(initial)setLoading(true);try{const d=await api(path,{signal:controller.signal});if(live&&request===serial){setData(d);setError('');}}catch(e){if(live&&e.name!=='AbortError')setError(e.message);}finally{if(live&&request===serial)setLoading(false);}};
  load(true);const timer=poll?setInterval(()=>load(false),poll):null;
  return()=>{live=false;controller.abort();if(timer)clearInterval(timer);};
 },[path,poll,revision]);
 const reload=useCallback(()=>setRevision(v=>v+1),[]);
 return {data,error,loading,reload};
}
function useDebounced(value){const [v,setV]=useState(value);useEffect(()=>{const t=setTimeout(()=>setV(value),300);return()=>clearTimeout(t);},[value]);return v;}
export function Teachers({app}){
 const [q,setQ]=useState(''),[language,setLanguage]=useState(''),[country,setCountry]=useState(''),[page,setPage]=useState(1),[course,setCourse]=useState(new URLSearchParams(location.search).get('course')||''),[courses,setCourses]=useState([]);
 const search=useDebounced(q),lang=useDebounced(language),params=new URLSearchParams({page,limit:9,q:search,language:lang,country,course});
 const {data,error,loading,reload}=useResource(`/teachers?${params}`);
 useEffect(()=>{let live=true;allPages(api,'/courses').then(d=>live&&setCourses(d)).catch(()=>{});return()=>{live=false;};},[]);
 const filter=(setter,value)=>{setter(value);setPage(1);};
 return <><PageHeader eyebrow="FIND THE RIGHT CONNECTION" title="Your teacher. Your time." description="Browse approved teachers, compare languages and experience, then view real availability in your own time zone."><Link app={app} to="/courses" className="btn outline">Explore all courses <Icon name="arrow" size={16}/></Link></PageHeader>
 <div className="directory-filters panel"><label className="field"><span>Find a teacher</span><input type="search" value={q} placeholder="Name or expertise" onChange={e=>filter(setQ,e.target.value)}/></label><label className="field"><span>Course</span><select value={course} onChange={e=>filter(setCourse,e.target.value)}><option value="">All courses</option>{courses.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select></label><label className="field"><span>Teaching language</span><input value={language} placeholder="e.g. Urdu or English" onChange={e=>filter(setLanguage,e.target.value)}/></label><label className="field"><span>Country</span><select value={country} onChange={e=>filter(setCountry,e.target.value)}><option value="">Any country</option>{countries.map(c=><option key={c.code}>{c.name}</option>)}</select></label></div>
 {loading?<Loading label="Finding your teachers…"/>:error?<Alert retry={reload}>{error}</Alert>:data?.items.length?<><div className="teacher-directory">{data.items.map(t=><TeacherSummary teacher={t} key={t._id}><Link app={app} to={`/teachers/${t._id}${course?'?course='+course:''}`} className="btn outline">Profile & availability</Link><Link app={app} to={`/enroll?teacher=${t._id}${course?'&course='+course:''}`} className="btn">Choose this teacher <Icon name="arrow" size={16}/></Link></TeacherSummary>)}</div><Pagination {...data} onChange={setPage}/></>:<Empty icon="users" title="No matching teachers yet" text="Try a different filter. Teachers appear after email verification and administrator approval."/>}
 </>;
}
export function SlotBoard({app,teacher,course,from,onFromChange,selected=[],onSelect,replaceEnrollment}){
 const zone=viewerZone(app.state.user),params=new URLSearchParams({timezone:zone,from,days:7});if(course)params.set('course',idOf(course));if(replaceEnrollment)params.set('replaceEnrollment',replaceEnrollment);
 const {data,error,loading,reload}=useResource(`/teachers/${teacher._id}/slots?${params}`,{poll:30000});
 const [onlyFree,setOnlyFree]=useState(false),[refreshStamp,setRefreshStamp]=useState('');
 useEffect(()=>{if(data)setRefreshStamp(new Date().toLocaleTimeString('en',{hour:'numeric',minute:'2-digit'}));},[data]);
 const groups=useMemo(()=>{const map={};for(let i=0;i<7;i++)map[shiftDate(from,i)]=[];for(const s of data?.slots||[]){const day=localDate(s.utcStart,zone);(map[day]||(map[day]=[])).push(s);}return Object.entries(map);},[data,from,zone]);
 return <section className="slot-section"><div className="slot-heading"><div><h2>Choose your weekly lesson times</h2><p>{data?.booking.slotMinutes||30}-minute lessons · displayed in <strong>{zone}</strong></p></div><Button variant="outline" icon="refresh" type="button" onClick={reload}>Refresh</Button></div>
 <div className="week-controls"><Button type="button" variant="outline" icon="left" disabled={from<=localDate(Date.now(),zone)} onClick={()=>onFromChange(shiftDate(from,-7)<localDate(Date.now(),zone)?localDate(Date.now(),zone):shiftDate(from,-7))}>Previous</Button><label className="field"><span>Starting week · your local date</span><input type="date" value={from} min={localDate(Date.now(),zone)} onChange={e=>e.target.value&&onFromChange(e.target.value)}/></label><Button type="button" variant="outline" icon="right" onClick={()=>onFromChange(shiftDate(from,7))}>Next week</Button></div>
 <div className="slot-legend"><span><i className="available-dot"/>Available</span><span><i className="held-dot"/>Held pending approval</span><span><i className="booked-dot"/>Booked / unavailable</span><label><input type="checkbox" checked={onlyFree} onChange={e=>setOnlyFree(e.target.checked)}/> Available only</label></div>
 {data?.legacyReview&&<Alert kind="info">An older active timetable needs administrator review before new recurring slots can be offered. Existing dated lessons remain in My timetable.</Alert>}{error&&<Alert retry={reload}>{error}</Alert>}{loading?<Loading label="Checking real bookings and recurring conflicts…"/>:data&&<><div className="slot-week">{groups.map(([day,slots])=><section className="slot-day" key={day}><h3>{dayTitle(day)}</h3><div className="slot-day-times">{slots.filter(s=>!onlyFree||s.status==='available').length?slots.filter(s=>!onlyFree||s.status==='available').map(s=>{
  const isSelected=selected.some(x=>x.key===s.key),disabled=s.status!=='available'||!onSelect;
  return <button key={s.key} type="button" className={`time-slot ${s.status} ${isSelected?'selected':''} ${!onSelect&&s.status==='available'?'view-only':''}`} disabled={disabled} aria-pressed={isSelected} title={s.reason||`Weekly ${s.day} ${s.startTime} in ${teacher.user.timezone}`} onClick={()=>onSelect?.(s)}><strong>{timeOnly(s.utcStart,zone)} – {timeOnly(s.utcEnd,zone)}</strong><small>{s.status==='available'?(isSelected?'Selected':'Available'):s.status==='held'?'Held':s.status==='booked'?'Booked':'Unavailable'}</small><span>Teacher: {titleCase(s.day).slice(0,3)} {s.startTime}</span>{s.conflictDate&&<span className="conflict-note">Conflict on {s.conflictDate}</span>}</button>;
 }):<p className="no-slot">No {onlyFree?'free ':''}slots</p>}</div></section>)}</div><div className="booking-policy"><Icon name="info" size={18}/><p>{data.recurrencePolicy} Minimum notice: {data.booking.bookingLeadHours} hours. A request holds slots for up to {data.booking.holdHours} hours, or until its first lesson. Last checked {refreshStamp}.</p></div></>}
 </section>;
}
export function TeacherProfile({app,id}){
 const {data:teacher,error,loading,reload}=useResource(`/teachers/${id}`),[from,setFrom]=useState(localDate(Date.now(),viewerZone(app.state.user))),course=new URLSearchParams(location.search).get('course')||'';
 if(loading)return <Loading/>;if(error)return <Alert retry={reload}>{error}</Alert>;if(!teacher)return null;
 return <><PageHeader eyebrow="MEET YOUR GUIDE" title={teacher.user.name} description="A complete teaching profile, with the teacher’s current time and real weekly availability."><Link app={app} to="/teachers" className="btn outline">All teachers</Link><Link app={app} to={`/enroll?teacher=${id}${course?'&course='+course:''}`} className="btn">Choose slots & request enrollment</Link></PageHeader><div className="teacher-detail-grid"><TeacherSummary teacher={teacher}/><div className="panel"><SectionTitle title="Teaching background"/>{teacher.qualifications?.length?<div className="qualification-list">{teacher.qualifications.map((q,i)=><div key={i}><Icon name="cap"/><div><strong>{q.degree}</strong><p>{q.institution}{q.year?' · '+q.year:''}</p></div></div>)}</div>:<p className="muted">No qualifications have been added to this profile yet.</p>}<h3 className="spaced-heading">Courses</h3><p>{teacher.courses?.length?teacher.courses.map(c=>c.name||'Course').join(' · '):'This teacher accepts requests for all active academy courses.'}</p></div></div><ZoneClocks yourZone={viewerZone(app.state.user)} teacherZone={teacher.user.timezone}/><SlotBoard app={app} teacher={teacher} course={course||null} from={from} onFromChange={setFrom}/><div className="bottom-cta"><p>Found a time that fits? Select a course, then choose your weekly slots.</p><Link app={app} to={`/enroll?teacher=${id}${course?'&course='+course:''}`} className="btn">Request enrollment <Icon name="arrow" size={16}/></Link></div></>;
}
export function Booking({app}){
 const params=new URLSearchParams(location.search),zone=viewerZone(app.state.user),[courseId,setCourseId]=useState(params.get('course')||''),[teacherId,setTeacherId]=useState(params.get('teacher')||''),replaceEnrollment=params.get('replaceEnrollment')||'';
 const [courses,setCourses]=useState([]),[teachers,setTeachers]=useState([]),[from,setFrom]=useState(localDate(Date.now(),zone)),[selected,setSelected]=useState([]),[notes,setNotes]=useState(''),[review,setReview]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[catalogLoading,setCatalogLoading]=useState(true);
 const {data:teacher,error:teacherError}=useResource(teacherId?`/teachers/${teacherId}`:null);
 const course=courses.find(c=>c._id===courseId);
 useEffect(()=>{let live=true;allPages(api,'/courses').then(d=>{if(live){setCourses(d);setCatalogLoading(false);}}).catch(e=>{if(live){setError(e.message);setCatalogLoading(false);}});return()=>{live=false;};},[]);
 useEffect(()=>{let live=true;setTeachers([]);allPages(api,`/teachers${courseId?'?course='+courseId:''}`).then(d=>live&&setTeachers(d)).catch(e=>live&&setError(e.message));return()=>{live=false;};},[courseId]);
 const body=()=>({course:courseId,ulma:teacherId,slots:selected.map(s=>s.utcStart),notes,...(replaceEnrollment?{replaceEnrollment}: {})});
 function chooseSlot(s){setReview(null);setError('');setSelected(old=>old.some(x=>x.key===s.key)?old.filter(x=>x.key!==s.key):[...old.filter(x=>x.day!==s.day),s].sort((a,b)=>new Date(a.utcStart)-new Date(b.utcStart)));}
 async function preview(){setBusy(true);setError('');try{setReview(await api('/enrollments/preview',{method:'POST',body:body()}));window.scrollTo({top:0,behavior:'smooth'});}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function submit(){setBusy(true);setError('');try{const d=await api('/enrollments',{method:'POST',body:body()});app.toast(d.message);app.navigate('/enrollments');}catch(e){setError(e.message);setReview(null);}finally{setBusy(false);}}
 return <><PageHeader eyebrow="BUILD YOUR LEARNING ROUTINE" title={review?'Review your learning plan.':'A course. A teacher. A time for you.'} description="Choose actual weekly slots. An administrator reviews your request before classes and monthly invoices are created."><Link app={app} to="/courses" className="btn outline">Back to courses</Link></PageHeader>
 <div className="booking-steps"><span className={course?'done':'active'}>1 · Course</span><span className={teacher?'done':course?'active':''}>2 · Teacher</span><span className={selected.length?'done':teacher?'active':''}>3 · Weekly slots</span><span className={review?'active':''}>4 · Review</span></div>
 {error&&<Alert>{error}</Alert>}{teacherError&&<Alert>{teacherError}</Alert>}{replaceEnrollment&&<Alert kind="info">This will replace your pending/expired request only when the new slots have been successfully reserved. Existing paid records are not deleted.</Alert>}
 {catalogLoading?<Loading/>:review?<div className="booking-review-grid"><section className="panel"><SectionTitle title="Your selected weekly lessons" subtitle={`Recurring in ${review.schedule.timeZone}, through ${review.schedule.untilDate} (end date exclusive).`}/><div className="selected-lessons">{selected.map(s=><div key={s.key}><Badge status="approved">{titleCase(s.day)} · {s.startTime} teacher time</Badge><DualTime start={s.utcStart} end={s.utcEnd} yourZone={zone} teacherZone={teacher.user.timezone}/></div>)}</div><SectionTitle title="First lessons in your timetable" subtitle={`${review.classCount} lessons in the course. The preview below shows up to 14.`}/><div className="preview-lesson-list">{review.classes.map(c=><p key={c.utcStart}>{rangeAt(c.utcStart,c.utcEnd,zone)}</p>)}</div>{review.skipped.length>0&&<Alert kind="info">{review.skipped.length} lesson time(s) fall in a clock-change gap/repeated hour and will not be scheduled automatically.<details><summary>View dates to review with your teacher</summary>{review.skipped.map((s,i)=><p key={i}>{s.date} {s.time} · {s.reason}</p>)}</details></Alert>}</section><aside className="panel booking-summary"><div className="eyebrow">ENROLLMENT SUMMARY</div><h2>{course?.name}</h2><p>With {teacher?.user.name}</p><div className="summary-price">{currency(review.monthlyFee,review.currency)}<small>per course month · {review.currency}</small></div><dl><div><dt>Lesson duration</dt><dd>{review.schedule.slotMinutes} minutes</dd></div><div><dt>Weekly lessons</dt><dd>{selected.length}</dd></div><div><dt>Course duration</dt><dd>{review.months} months</dd></div><div><dt>Scheduled lessons</dt><dd>{review.classCount}</dd></div><div><dt>Monthly invoices</dt><dd>{review.invoices.length}</dd></div></dl><p className="form-note">Approval creates the full timetable and one dated invoice per course month. This is not a payment or automatic charge. Currency is not converted based on your country.</p><Button disabled={busy} icon="check" onClick={submit}>{busy?'Reserving your slots…':'Send request to administrator'}</Button><Button variant="outline" disabled={busy} onClick={()=>setReview(null)}>Back to slot selection</Button></aside></div>:
 <div className="booking-layout"><div className="booking-main"><section className="panel booking-selectors"><label className="field"><span>1. Choose your course</span><select value={courseId} disabled={!!replaceEnrollment} onChange={e=>{setCourseId(e.target.value);setTeacherId('');setSelected([]);setReview(null);}}><option value="">Select a published course</option>{courses.map(c=><option key={c._id} value={c._id}>{c.name} · {currency(c.monthlyFee,c.currency)}/month</option>)}</select></label><label className="field"><span>2. Choose your teacher</span><select value={teacherId} disabled={!!replaceEnrollment} onChange={e=>{setTeacherId(e.target.value);setSelected([]);setReview(null);}}><option value="">Select an approved teacher</option>{teachers.map(t=><option key={t._id} value={t._id}>{t.user.name} · {(t.user.languages||[]).map(titleCase).join(', ')} · {t.user.timezone}</option>)}</select></label></section>
 {teacher&&<><TeacherSummary teacher={teacher} compact/><ZoneClocks yourZone={zone} teacherZone={teacher.user.timezone}/></>}
 {course&&teacher?<SlotBoard app={app} teacher={teacher} course={course} from={from} onFromChange={v=>{setFrom(v);setSelected([]);setReview(null);}} selected={selected} onSelect={chooseSlot} replaceEnrollment={replaceEnrollment}/>:<Empty icon="calendar" title="Your weekly routine starts here" text="Select a course and a teacher above to see bookable lessons in your local time zone."/>}
 </div><aside className="panel booking-summary"><div className="eyebrow">YOUR LEARNING PLAN</div><h2>{course?.name||'Select your course'}</h2>{course&&<><p>{course.duration} months · {course.level}</p><div className="summary-price">{currency(course.monthlyFee,course.currency)}<small>per month · {course.currency||'PKR'}</small></div></>}<h3>{selected.length?`${selected.length} weekly slot${selected.length>1?'s':''} selected`:'Choose your weekly slots'}</h3><p className="muted">At most one slot per teacher weekday. Selecting another time on that weekday replaces the previous one.</p><div className="selected-mini">{selected.map(s=><div key={s.key}><span>{atZone(s.utcStart,zone)}</span><button className="icon-btn" title="Remove selected time" aria-label="Remove selected time" onClick={()=>chooseSlot(s)}><Icon name="close" size={16}/></button></div>)}</div><label className="field"><span>Learning goals / notes</span><textarea value={notes} maxLength={1000} rows={3} onChange={e=>setNotes(e.target.value)} placeholder="Tell your teacher what you would like to focus on."/></label><Button disabled={busy||!course||!teacher||!selected.length} icon="arrow" onClick={preview}>{busy?'Checking all recurring dates…':'Review enrollment'}</Button><small>Selected slots are rechecked on the server before they are reserved.</small></aside></div>}
 </>;
}

export function Enrollments({app}){
 const role=app.state.user.role,zone=viewerZone(app.state.user),[page,setPage]=useState(1),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(null),[error,setError]=useState('');
 const {data,loading,error:loadError,reload}=useResource(`/enrollments?${new URLSearchParams({page,limit:10,status})}`,{poll:20000});
 async function act(e,next){setBusy(true);setError('');try{const r=await api(`/enrollments/${e._id}`,{method:'PATCH',body:{status:next}});setConfirm(null);app.toast(r.message||'Enrollment updated.');reload();}catch(err){setError(err.message);}finally{setBusy(false);}}
 const ask=(e,next)=>{setError('');setConfirm({e,next});};
 return <><PageHeader eyebrow="REQUEST TO ROUTINE" title={role==='admin'?'Enrollment approvals.':'Your learning connections.'} description={role==='admin'?'Review the selected teacher, weekly slots and fees. Approval atomically creates the timetable and dated monthly invoices.':'Track your selected slots, administrator approval and learning schedule.'}>{role==='student'&&<Link app={app} to="/courses" className="btn">Find a course <Icon name="plus" size={16}/></Link>}</PageHeader>
 <div className="resource-toolbar"><label className="field"><span>Enrollment status</span><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All enrollments</option>{['pending','approved','active','paused','expired','completed','cancelled','rejected'].map(s=><option key={s} value={s}>{titleCase(s)}</option>)}</select></label><Button variant="outline" icon="refresh" onClick={reload}>Refresh</Button></div>{error&&!confirm&&<Alert>{error}</Alert>}
 {loading?<Loading/>:loadError?<Alert retry={reload}>{loadError}</Alert>:!data?.items.length?<Empty icon="cap" title="No enrollments here yet" text="Choose a published course, a teacher and weekly slots to request enrollment."/>:<><div className="enrollment-grid">{data.items.map(e=>{
  const t=e.ulma?.user,s=e.student?.user,legacy=!e.schedule?.slots?.length,requestAgain=['pending','expired'].includes(e.status),active=['approved','active','paused'].includes(e.status);
  return <article className="panel enrollment-panel" key={e._id}><div className="record-heading"><div><div className="eyebrow">{e._id.slice(-8).toUpperCase()}</div><h2>{e.course?.name||'Course unavailable'}</h2></div><Badge status={e.status}/></div><div className="enrollment-people"><Avatar user={t}/><div><strong>{t?.name||'Teacher'}</strong><p>Teacher · {t?.timezone||'Time zone not set'}</p></div>{role!=='student'&&<div><strong>{s?.name||'Student'}</strong><p>Student · {s?.timezone||'Time zone not set'}</p></div>}</div>
  <div className="enrollment-meta"><span>{currency(e.monthlyFee,e.currency||e.course?.currency)} / month</span><span>{e.courseDuration||e.course?.duration} months</span>{!legacy&&<span>{e.schedule.slotMinutes}-minute lessons</span>}</div>
  {legacy?<Alert kind="info">This older enrollment has no saved weekly slots. Existing records remain unchanged. A pending request must have slots selected before automatic approval.</Alert>:<div className="enrolled-slots">{(e.schedule.firstOccurrences||[]).map((o,i)=><div key={i}><strong>Weekly {titleCase(o.day)} · {o.startTime} ({e.schedule.timeZone})</strong><DualTime start={o.utcStart} end={o.utcEnd} yourZone={zone} teacherZone={e.schedule.timeZone} studentZone={s?.timezone}/></div>)}{!e.schedule.firstOccurrences?.length&&e.schedule.slots.map((o,i)=><p key={i}>{titleCase(o.day)} {o.startTime} · {e.schedule.timeZone}</p>)}<small>The dates above are the initial occurrences. Open the timetable for each actual date, including daylight-saving changes.</small></div>}
  {e.status==='pending'&&e.holdExpiresAt&&<p className="hold-note"><Icon name="clock" size={15}/> Hold expires {atZone(e.holdExpiresAt,zone)}</p>}{e.generatedAt&&<p className="generated-note"><Icon name="check" size={16}/>{e.classesCount} lessons · {e.invoiceCount} monthly invoices generated</p>}{e.notes&&<p className="enrollment-notes">{e.notes}</p>}{e.schedule?.skipped?.length>0&&<details><summary>{e.schedule.skipped.length} DST exception(s)</summary>{e.schedule.skipped.map((d,i)=><p key={i}>{d.date} {d.time} · {d.reason}</p>)}</details>}
  <div className="record-actions">{active&&<Link app={app} to="/classes" className="btn outline">Open timetable</Link>}{active&&role==='student'&&<Link app={app} to="/fees" className="btn outline">Fee invoices</Link>}
  {role==='admin'&&e.status==='pending'&&<><Button disabled={busy||legacy} icon="check" onClick={()=>ask(e,'approved')}>Approve enrollment</Button><Button variant="outline" disabled={busy} onClick={()=>ask(e,'rejected')}>Reject</Button></>}
  {role==='admin'&&['approved','active'].includes(e.status)&&<Button variant="outline" disabled={busy} onClick={()=>ask(e,'paused')}>Pause</Button>}{role==='admin'&&e.status==='paused'&&<Button disabled={busy} onClick={()=>ask(e,'active')}>Resume</Button>}
  {role==='admin'&&['approved','active','paused'].includes(e.status)&&<Button variant="outline" disabled={busy} onClick={()=>ask(e,'completed')}>Complete enrollment</Button>}{role==='student'&&requestAgain&&<Link app={app} className="btn outline" to={`/enroll?course=${idOf(e.course)}&teacher=${idOf(e.ulma)}&replaceEnrollment=${e._id}`}>{legacy?'Choose slots':'Choose slots / request again'}</Link>}
  {['admin','student'].includes(role)&&['pending','approved','active','paused','expired'].includes(e.status)&&<Button variant="outline" disabled={busy} onClick={()=>ask(e,'cancelled')}>Cancel enrollment</Button>}</div></article>;
 })}</div><Pagination {...data} onChange={setPage}/></>}
 {confirm&&<Modal title={confirm.next==='approved'?'Approve this learning plan?':`${titleCase(confirm.next)} enrollment?`} busy={busy} onClose={()=>setConfirm(null)}>{error&&<Alert>{error}</Alert>}<p>{confirm.next==='approved'?`This will reserve the selected weekly slots, generate the full course timetable for student and teacher, and create ${confirm.e.courseDuration||confirm.e.course?.duration} monthly invoices at ${currency(confirm.e.monthlyFee,confirm.e.currency||'PKR')}. No payment is charged.`:confirm.next==='paused'?'Live and future lessons pause, but the student keeps their reserved slots. Invoices are not automatically refunded or prorated.':confirm.next==='cancelled'?'Future lessons will be cancelled and their slots released. Future unsubmitted automatic invoices are cancelled; paid invoices and historical records stay unchanged.':'The enrollment status will be updated and both participants notified.'}</p><div className="modal-actions"><Button variant="outline" disabled={busy} onClick={()=>setConfirm(null)}>Go back</Button><Button disabled={busy} onClick={()=>act(confirm.e,confirm.next)}>{busy?'Saving atomically…':'Confirm'}</Button></div></Modal>}
 </>;
}

export function Timetable({app}){
 const user=app.state.user,zone=viewerZone(user),teacher=user.role==='ulma';
 const [bucket,setBucket]=useState('upcoming'),[page,setPage]=useState(1),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[modal,setModal]=useState(null),[confirm,setConfirm]=useState(null);
 const {data,error:loadError,loading,reload}=useResource(`/classes?${new URLSearchParams({bucket,page,limit:12,from,to})}`,{poll:5000});
 useEffect(()=>{
  let socket;const changed=()=>reload();
  const unsub=app.subscribeSocket?.(next=>{socket?.off('classes:changed',changed);socket=next;socket?.on('classes:changed',changed);});
  window.addEventListener('focus',changed);
  return()=>{socket?.off('classes:changed',changed);unsub?.();window.removeEventListener('focus',changed);};
 },[app,reload]);
 async function start(c){
  setBusy(c._id);setError('');
  try{await api(`/classes/${c._id}/start`,{method:'POST',body:{}});app.navigate(`/class/${c._id}?join=1`);}
  catch(e){setError(e.message);reload();}finally{setBusy('');}
 }
 async function openCreate(){
  setBusy('create');setError('');
  try{const enrollments=(await allPages(api,'/enrollments')).filter(e=>['approved','active'].includes(e.status));if(!enrollments.length)throw new Error('You need an approved enrollment before scheduling a class.');setModal({kind:'create',enrollments});}
  catch(e){setError(e.message);}finally{setBusy('');}
 }
 async function save(body){
  const result=modal.kind==='create'?await api('/classes',{method:'POST',body}):await api(`/classes/${modal.lesson._id}`,{method:'PATCH',body});
  const created=modal.kind==='create';setModal(null);app.toast(created?'Class scheduled. Both participants can now open its details.':'Lesson details saved.');reload();
  if(created)app.navigate(`/class/${result._id}`);
 }
 async function changeStatus(c,status){
  setBusy(c._id);setError('');
  try{const result=await api(`/classes/${c._id}`,{method:'PATCH',body:{status}});setConfirm(null);reload();if(result.warning)setError(result.warning);else app.toast('Lesson updated.');}
  catch(e){setError(e.message);}finally{setBusy('');}
 }
 const nameField={name:'topic',label:'Class name',required:true,minLength:2,maxLength:160,full:true};
 const notesField={name:'notes',label:'Lesson description','type':'textarea',full:true,maxLength:2000};
 const fields=modal?.kind==='create'?[
  {name:'enrollment',label:'Approved enrollment',type:'select',required:true,full:true,options:modal.enrollments.map(e=>({value:e._id,label:`${e.course?.name} · ${e.student?.user?.name}`}))},nameField,
  {name:'localDate',label:`Date in ${zone}`,type:'date',required:true,defaultValue:localDate(Date.now(),zone)},
  {name:'startTime',label:`Start time in ${zone}`,type:'time',required:true},notesField
 ]:[nameField,notesField];
 return <><PageHeader eyebrow="TIME TO LEARN, TOGETHER" title="Your classes & timetable." description={`Times are shown in ${zone}. Every class has its own page. Student joining unlocks only after the teacher starts; this list refreshes every 5 seconds.`}>
  {teacher&&<Button icon="plus" disabled={!!busy} onClick={openCreate}>Schedule a class</Button>}<Button variant="outline" icon="refresh" onClick={reload}>Refresh</Button>
 </PageHeader><ZoneClocks yourZone={zone}/>
 <div className="class-filters panel"><div className="class-tabs" role="tablist" aria-label="Class status">
  {[['upcoming','Upcoming'],['live','Live now'],['history','Past lessons'],['cancelled','Cancelled'],['all','All classes']].map(([v,label])=><button type="button" role="tab" aria-selected={bucket===v} className={bucket===v?'active':''} key={v} onClick={()=>{setBucket(v);setPage(1);}}>{label}</button>)}
 </div><div className="date-filters"><label className="field"><span>From · local date</span><input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/></label><label className="field"><span>Through · local date</span><input type="date" value={to} min={from} onChange={e=>{setTo(e.target.value);setPage(1);}}/></label>{(from||to)&&<Button variant="outline" onClick={()=>{setFrom('');setTo('');setPage(1);}}>Clear dates</Button>}</div></div>
 {error&&!confirm&&<Alert>{error}</Alert>}
 {loading&&!data?<Loading/>:loadError?<Alert retry={reload}>{loadError}</Alert>:!data?.items.length?<Empty icon="calendar" title="No lessons in this view" text={teacher?'Schedule a class for an approved enrollment, or choose another date range.':'Your teacher’s scheduled classes will appear here. You can also open All classes.'}/>:<>
 <div className="lesson-grid">{data.items.map(c=><article className="panel lesson-card" key={c._id}>
  <div className="record-heading"><div><div className="eyebrow">{c.course?.name||'Lesson'}</div><h2><Link app={app} to={`/class/${c._id}`}>{c.topic}</Link></h2></div><Badge status={c.status}>{c.isExpired&&c.status==='ongoing'?'Time ended':c.status}</Badge></div>
  <div className="lesson-people"><Avatar user={c.ulma?.user}/><div><strong>{c.ulma?.user?.name||'Teacher'}</strong><small>Teacher</small></div><div><strong>{c.student?.user?.name||'Student'}</strong><small>Student</small></div></div>
  <DualTime start={c.utcStart} end={c.utcEnd} yourZone={zone} teacherZone={c.teacherTimeZone||c.ulma?.user?.timezone} studentZone={c.student?.user?.timezone}/>
  <div className="lesson-kind"><span>{c.slotMinutes||Math.round((new Date(c.utcEnd)-new Date(c.utcStart))/60000)} minutes</span><span>Embedded private classroom</span>{c.autoGenerated&&<span>Recurring lesson</span>}</div>
  {c.notes&&<p className="lesson-notes">{c.notes}</p>}<p className="room-id-caption">Room ID · {c.roomId}</p>
  <div className="record-actions">
   {teacher&&c.canStart&&<Button icon="play" disabled={!!busy} onClick={()=>start(c)}>{busy===c._id?'Preparing room…':'Start Class'}</Button>}
   {c.canJoin&&<Link app={app} to={`/class/${c._id}?join=1`} className="btn">Join Class <Icon name="video" size={16}/></Link>}
   <Link app={app} to={`/class/${c._id}`} className="btn outline">Class details</Link>
   {c.status==='scheduled'&&!c.canStart&&<span className="join-hint"><Icon name="clock" size={16}/>{c.isExpired?'The scheduled time has passed.':teacher?`Start opens ${atZone(c.joinOpensAt,zone)}`:'Waiting for your teacher to start.'}</span>}
   {c.status==='paused'&&<span className="join-hint">Enrollment paused · slot remains reserved</span>}
   {teacher&&c.canEdit&&<Button variant="outline" disabled={!!busy} onClick={()=>setModal({kind:'edit',lesson:c})}>Edit details</Button>}
   {teacher&&c.status==='ongoing'&&<Button variant="outline" disabled={!!busy} onClick={()=>setConfirm({c,status:'completed'})}>End Class</Button>}
   {teacher&&['scheduled','paused','ongoing'].includes(c.status)&&<Button variant="outline" disabled={!!busy} onClick={()=>setConfirm({c,status:'cancelled'})}>Cancel lesson</Button>}
   {teacher&&c.closePending&&<Link app={app} to={`/class/${c._id}`} className="text-link">Video cleanup needs attention</Link>}
  </div>
 </article>)}</div><Pagination {...data} onChange={setPage}/></>}
 {modal&&<Modal title={modal.kind==='create'?'Schedule a class':'Edit class details'} onClose={()=>setModal(null)}><p className="form-note">{modal.kind==='create'?`Enter a class name, date and start time in ${zone}. Duration is ${data?.booking?.slotMinutes||30} minutes. The backend generates the room ID; do not create a Daily room or paste a meeting link. Overlapping teacher/student bookings are rejected.`:'Update the name and description. To move a lesson, cancel it and schedule a replacement. Billing is not automatically adjusted.'}</p><DataForm fields={fields} values={modal.lesson||{}} onSubmit={save} label={modal.kind==='create'?'Schedule class':'Save details'}/></Modal>}
 {confirm&&<Modal title={confirm.status==='completed'?'End this class?':'Cancel this class?'} busy={!!busy} onClose={()=>setConfirm(null)}>{error&&<Alert>{error}</Alert>}<p>{confirm.status==='completed'?'New joins close immediately and Daily is asked to disconnect both participants. Attendance can still be recorded.':'This lesson will be cancelled and its slot released. Other weekly lessons stay unchanged. No refund is issued automatically.'}</p><div className="modal-actions"><Button variant="outline" disabled={!!busy} onClick={()=>setConfirm(null)}>Go back</Button><Button disabled={!!busy} onClick={()=>changeStatus(confirm.c,confirm.status)}>{busy?'Saving…':'Confirm'}</Button></div></Modal>}
 </>;
}
