// export { default as QuranReader } from "./QuranReader";
// export { default as QuranSearch } from "./QuranSearch";
// export { default as AudioPlayer } from "./AudioPlayer";
// export { default as SurahList } from "./SurahList";
// export { default as BookmarksPanel } from "./BookmarksPanel";
// export { default as StatisticsPanel } from "./StatisticsPanel";
// export { default as SettingsPanel } from "./SettingsPanel";
// export { default as NavigationBar } from "./NavigationBar";
// export { default as TafsirPanel } from "./TafsirPanel";
